stages:
  - setup
  - build
  - deploy

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - vendor
    - bin
    - node_modules

after_script:
  - docker-compose down

variables:
  WEB_PORT: 8008
  MYSQL_PORT: 6603

#################
###   Setup   ###
#################
setup:env:
  stage: setup
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry-gitlab.novaway.net
    - docker-compose pull
    - make vendors
  tags:
    - shell
  only:
    - develop
    - tags

#################
###   Build   ###
#################
build:assets:
  stage: build
  dependencies:
    - setup:env
  script:
    - make front
    - make api-documentation
  tags:
    - shell
  artifacts:
    paths:
      - web/assets/bundle
  only:
    - develop
    - tags

#################
###  Deploy   ###
#################
deploy:demo:
  stage: deploy
  dependencies:
    - setup:env
    - build:assets
  script:
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy --hosts demo"
  tags:
    - shell
  environment:
    name: Demo
    url: https://demo-wamcar.novaway.net
  only:
    - develop

deploy:staging:
  stage: deploy
  dependencies:
    - setup:env
    - build:assets
  script:
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy --hosts staging --tag=$CI_COMMIT_TAG"
  tags:
    - shell
  environment:
    name: Staging
    url: http://wamcar.staging.novaway.net
  only:
    - tags

deploy:demo:unlock:
  stage: deploy
  dependencies:
    - setup:env
  script:
    - make vendors
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy:unlock --hosts demo"
  tags:
    - shell
  when: manual
  only:
    - develop

deploy:staging:unlock:
  stage: deploy
  dependencies:
    - setup:env
  script:
    - make vendors
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy:unlock --hosts staging"
  tags:
    - shell
  when: manual
  only:
    - tags
