stages:
  - deploy

before_script:
  - mv docker-compose.yml docker-compose.yml.origin
  - sed "s/:cached/:consistent/g" docker-compose.yml.origin > docker-compose.yml
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry-gitlab.novaway.net
  - make vendors
  - make front
  - make api-documentation
after_script:
  - docker-compose down

cache:
  paths:
    - docker-compose.yml
    - vendor
    - bin
    - node_modules
  policy: pull-push

variables:
  WEB_PORT: 8008
  MYSQL_PORT: 6603
  USER_ID: $CI_RUNNER_ID

#################
###  Deploy   ###
#################
deploy:demo:
  stage: deploy
  script:
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy --hosts demo"
  tags:
    - shell
  environment:
    name: Demo
    url: https://demo-wamcar.novaway.net
  only:
    - develop

deploy:staging:
  stage: deploy
  script:
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy --hosts staging --tag=$CI_COMMIT_TAG"
  tags:
    - shell
  environment:
    name: Staging
    url: http://wamcar.staging.novaway.net
  only:
    - tags

deploy:demo:unlock:
  stage: deploy
  script:
    - make vendors
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy:unlock --hosts demo"
  tags:
    - shell
  when: manual
  only:
    - develop

deploy:staging:unlock:
  stage: deploy
  script:
    - make vendors
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy:unlock --hosts staging"
  tags:
    - shell
  when: manual
  only:
    - tags
