stages:
  - setup
  - build
  - deploy

after_script:
  - docker-compose down

.job_template: &cache_writer
  cache:
    key: "wamcar-$CI_COMMIT_SHA"
    paths:
      - docker-compose.yml
      - vendor
      - bin
      - node_modules
    policy: pull-push

.job_template: &cache_reader
  cache:
    key: "wamcar-$CI_COMMIT_SHA"
    paths:
      - docker-compose.yml
      - vendor
      - bin
      - node_modules
    policy: pull

variables:
  WEB_PORT: 8008
  MYSQL_PORT: 6603

#################
###   Setup   ###
#################
setup:env:
  <<: *cache_writer
  stage: setup
  script:
    - mv docker-compose.yml docker-compose.yml.origin
    - sed "s/:cached/:consistent/g" docker-compose.yml.origin > docker-compose.yml
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry-gitlab.novaway.net
    - docker-compose pull
    - make vendors
  tags:
    - shell
  only:
    - develop
    - tags

#################
###   Build   ###
#################
build:assets:
  <<: *cache_writer
  stage: build
  dependencies:
    - setup:env
  script:
    - make api-documentation
    - make front
  tags:
    - shell
  artifacts:
    paths:
      - web/assets/bundle
      - web/openapi.json
  only:
    - develop
    - tags

#################
###  Deploy   ###
#################
deploy:demo:
  <<: *cache_reader
  stage: deploy
  dependencies:
    - setup:env
    - build:assets
  script:
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy --hosts demo"
  tags:
    - shell
  environment:
    name: Demo
    url: https://demo-wamcar.novaway.net
  only:
    - develop

deploy:staging:
  <<: *cache_reader
  stage: deploy
  dependencies:
    - setup:env
    - build:assets
  script:
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy --hosts staging --tag=$CI_COMMIT_TAG"
  tags:
    - shell
  environment:
    name: Staging
    url: http://wamcar.staging.novaway.net
  only:
    - tags

deploy:demo:unlock:
  <<: *cache_reader
  stage: deploy
  dependencies:
    - setup:env
  script:
    - make vendors
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy:unlock --hosts demo"
  tags:
    - shell
  when: manual
  only:
    - develop

deploy:staging:unlock:
  <<: *cache_reader
  stage: deploy
  dependencies:
    - setup:env
  script:
    - make vendors
    - docker-compose run --rm php bash -c "git config user.name novaway && bin/dep deploy:unlock --hosts staging"
  tags:
    - shell
  when: manual
  only:
    - tags
