staging:
    stage: staging
    hostname: novaway2bis.netsample.com
    user: staging
    multiplexing: false
    deploy_path: /var/www/vhosts/staging.novaway.net/wamcar
    http_user: apache
    url: http://wamcar.staging.novaway.net
    bin/php: "/opt/plesk/php/7.1/bin/php"
    bin/composer: "{{bin/php}} {{release_path}}/composer.phar"
    composer_options: "{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --dev --optimize-autoloader"

demo:
    stage: demo
    hostname: 192.168.10.101
    user: demo
    branch: develop
    multiplexing: false
    deploy_path: /home/demo/public/wamcar
    http_user: apache
    url: https://demo-wamcar.novaway.net
    bin/php: "/opt/remi/php71/root/bin/php"
    bin/composer: "{{bin/php}} {{release_path}}/composer.phar"
    composer_options: "{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --dev --optimize-autoloader"
