staging:
    stage: staging
    hostname: novaway2bis.netsample.com
    user: staging
    branch: staging
    multiplexing: false
    deploy_path: /var/www/vhosts/staging.novaway.net/wamcar
    http_user: apache
    url: http://wamcar.staging.novaway.net
