Wamcar\Conversation\Message:

    type: entity
    table: conversation_message

    repositoryClass: AppBundle\Doctrine\Repository\DoctrineMessageRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        content:
            type: text
        isFleet:
            type: boolean
        publishedAt:
            type: datetime

    manyToOne:
        conversation:
            targetEntity: Conversation
            inversedBy: messages
            joinColumn:
                name: conversation_id
                referencedColumnName: id
        user:
            targetEntity: Wamcar\User\BaseUser
            inversedBy: messages
            joinColumn:
                name: user_id
                referencedColumnName: id
        proVehicleHeader:
            targetEntity: Wamcar\Vehicle\ProVehicle
            inversedBy: headerMessages
            joinColumn:
                name: pro_vehicle_header_id
                referencedColumnName: id
        personalVehicleHeader:
            targetEntity: Wamcar\Vehicle\PersonalVehicle
            inversedBy: headerMessages
            joinColumn:
                name: personal_vehicle_header_id
                referencedColumnName: id
        proVehicle:
            targetEntity: Wamcar\Vehicle\ProVehicle
            inversedBy: messages
            joinColumn:
                name: pro_vehicle_id
                referencedColumnName: id
        personalVehicle:
            targetEntity: Wamcar\Vehicle\PersonalVehicle
            inversedBy: messages
            joinColumn:
                name: personal_vehicle_id
                referencedColumnName: id
