Wamcar\Conversation\Conversation:

    type: entity
    table: conversation
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        basic: Wamcar\Conversation\Conversation
        application: AppBundle\Doctrine\Entity\ApplicationConversation
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineConversationRepository

    id:
        id:
            type: uuid

    fields:

    oneToMany:
        conversationUsers:
            targetEntity: ConversationUser
            mappedBy: conversation
            cascade: ["persist", "merge", "remove"]
        messages:
            targetEntity: Message
            mappedBy: conversation
            cascade: ["persist", "merge", "remove"]
