Wamcar\Conversation\ConversationUser:

    type: entity
    table: conversation_user

    repositoryClass: AppBundle\Doctrine\Repository\DoctrineConversationUserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        lastOpenedAt:
            type: datetime

    manyToOne:
        conversation:
            targetEntity: AppBundle\Doctrine\Entity\ApplicationConversation
            inversedBy: conversationUsers
            joinColumn:
                name: conversation_id
                referencedColumnName: id
        user:
            targetEntity: Wamcar\User\BaseUser
            inversedBy: conversationUsers
            joinColumn:
                name: user_id
                referencedColumnName: id
