Wamcar\Conversation\ConversationUser:

    type: entity
    table: conversation_user

    repositoryClass: AppBundle\Doctrine\Repository\ConversationUserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        lastOpenAt:
            type: datetime

    manyToOne:
        conversation:
            targetEntity: Conversation
            inversedBy: conversationUsers
            joinColumn:
                name: conversation_id
                referencedColumnName: id
        user:
            targetEntity: Wamcar\User\BaseUser
            inversedBy: userConversations
            joinColumn:
                name: user_id
                referencedColumnName: id
        messages:
            targetEntity: Message
            mappedBy: conversationUser
            cascade: ["persist", "merge", "remove"]
