Wamcar\Garage\GarageProUser:

    type: entity
    table: garage_pro_user
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineGarageProUserRepository

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [garage, proUser]
            errorPath: proUser
            message: 'This proUser is already in use on that garage.'

    id:
      garage:
        associationKey: true
      proUser:
        associationKey: true

    fields:
      role:
        type: garagerole
        nullable: false
      requestedAt:
        type: datetime
        nullable: true

    manyToOne:
      garage:
        targetEntity: Wamcar\Garage\Garage
        inversedBy: members
        joinColumn:
          name: garage_id
          referencedColumnName: id

      proUser:
        targetEntity: Wamcar\User\ProUser
        inversedBy: garageMemberships
        joinColumn:
          name: pro_user_id
          referencedColumnName: id