Wamcar\Garage\Address:
    type: embeddable

    embedded:
        city:
            class: Wamcar\Location\City
            columnPrefix: city_

    fields:
        address:
            type: string
            nullable: true
