Wamcar\Location\City:
    type: embeddable

    fields:
        postalCode:
            type: string
            nullable: true
        name:
            type: string
            nullable: true
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true
