Wamcar\Sale\Declaration:
  type: entity
  table: sale_declaration
  repositoryClass: AppBundle\Doctrine\Repository\DoctrineSaleDeclarationRepository
  exclusion_policy: ALL
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  id:
      id:
          type: uuid

  fields:
    sellerFirstName:
      type: string
      nullable: true
    sellerLastName:
      type: string
      nullable: true
    buyerFirstName:
      type: string
      nullable: true
    buyerLastName:
      type: string
      nullable: true
    transactionAmount:
      type: integer
      nullable: true
    creditEarned:
      type: integer
      nullable: true
    deletedAt:
      type: date
      nullable: true
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update


  manyToOne:
    proUserSeller:
      targetEntity: Wamcar\User\ProUser
      inversedBy: saleDeclarations
      joinColumn:
        name: pro_user_seller_id
        referencedColumnName: id
        nullable: false
    leadBuyer:
      targetEntity: Wamcar\User\Lead
      inversedBy: saleDeclarations
      joinColumn:
        name: lead_id
        referencedColumnName: id
        nullable: true