Wamcar\User\BaseLikeVehicle:

    type: entity
    inheritanceType: SINGLE_TABLE
    table: user_like_vehicle
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        personal: Wamcar\User\PersonalLikeVehicle
        pro: Wamcar\User\ProLikeVehicle
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false

    exclusion_policy: ALL
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineUserLikeVehicleRepository

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user, vehicle]
            errorPath: proUser
            message: 'This user is already liking this vehicle.'

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        value:
            type: smallint
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: date
            nullable: true

    manyToOne:
        user:
            targetEntity: Wamcar\User\BaseUser
            inversedBy: likes
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false

