Wamcar\User\BaseUser:

    type: entity
    inheritanceType: SINGLE_TABLE
    table: user
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        basic-pro: Wamcar\User\ProUser
        basic-personal: Wamcar\User\PersonalUser
        pro: AppBundle\Doctrine\Entity\ProApplicationUser
        personal: AppBundle\Doctrine\Entity\PersonalApplicationUser
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false

    exclusion_policy: ALL
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineUserRepository

    embedded:
        userProfile:
            class: Wamcar\User\UserProfile
            columnPrefix: profile_

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        deletedAt:
            type: date
            nullable: true
        email:
            type: string
            length: 191   # needed to index field in utf8mb4
            unique: true
        facebookId:
            type: string
            length: 255
            nullable: true
        facebookAccessToken:
            type: string
            length: 255
            nullable: true
        linkedinId:
            type: string
            length: 255
            nullable: true
        linkedinAccessToken:
            type: string
            length: 255
            nullable: true
        googleId:
            type: string
            length: 255
            nullable: true
        googleAccessToken:
            type: string
            length: 255
            nullable: true
        twitterId:
            type: string
            length: 255
            nullable: true
        twitterAccessToken:
            type: string
            length: 255
            nullable: true
        apiClientId:
            type: string
            nullable: true
        apiSecret:
            type: string
            nullable: true
        firstContactPreference:
            type: firstcontactpreference
            nullable: true
        deletionReason:
            type: text
            nullable: true
        creditPoints:
            type: integer
            nullable: false
        youtubeVideoId:
            type: string
            nullable: true
        videoShortText:
            type: text
            nullable: true
        videoText:
            type: text
            nullable: true

    oneToOne:
        avatar:
            targetEntity: AppBundle\Doctrine\Entity\UserPicture
            inversedBy: user
            joinColumn:
                name: avatar_id
                referencedColumnName: id
            cascade: ["persist", "merge", "remove"]
        banner:
            targetEntity: AppBundle\Doctrine\Entity\UserBanner
            inversedBy: user
            joinColumn:
                name: banner_id
                referencedColumnName: id
            cascade: ["persist", "merge", "remove"]
        preferences:
            targetEntity: AppBundle\Doctrine\Entity\UserPreferences
            mappedBy: user
            cascade: ["persist","merge","remove"]
        affinityAnswer:
            targetEntity: TypeForm\Doctrine\Entity\AffinityAnswer
            mappedBy: user
            cascade: ["persist","merge","remove"]
    oneToMany:
        conversationUsers:
            targetEntity: Wamcar\Conversation\ConversationUser
            mappedBy: user
            cascade: ["persist", "merge"]
        messages:
            targetEntity: Wamcar\Conversation\Message
            mappedBy: user
            cascade: ["persist", "merge"]
        likes:
            targetEntity: Wamcar\User\BaseLikeVehicle
            mappedBy: user
            cascade: ["persist", "merge", "remove"]
            orderBy:
                updatedAt: "desc"
        smallerIdUserAffinityDegrees:
            targetEntity: AppBundle\Doctrine\Entity\AffinityDegree
            mappedBy: greaterIdUser
            cascade: ["persist", "merge", "remove"]
        greaterIdUserAffinityDegrees:
            targetEntity: AppBundle\Doctrine\Entity\AffinityDegree
            mappedBy: smallerIdUser
            cascade: ["persist", "merge", "remove"]
    manyToMany:
        myExperts:
            targetEntity: Wamcar\User\BaseUser
            mappedBy: expertOf
            cascade: ["persist", "merge", "remove"]
        expertOf:
            targetEntity:  Wamcar\User\BaseUser
            inversedBy: myExperts
            joinTable:
                name: experts
                joinColumns:
                    expert_user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id

