Wamcar\User\PersonalUser:
    type: entity

    oneToMany:
        vehicles:
            targetEntity: Wamcar\Vehicle\PersonalVehicle
            mappedBy: personalUser
            cascade: ["persist", "merge", "remove"]