Wamcar\User\City:
    type: embeddable
    columnPrefix: city_
    fields:
        postalCode:
            type: string
            nullable: false
        name:
            type: string
            nullable: false
