Wamcar\User\BaseUser:

    type: entity
    inheritanceType: SINGLE_TABLE
    table: user
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        basic-pro: Wamcar\User\ProUser
        basic-personal: Wamcar\User\PersonalUser
        pro: AppBundle\Doctrine\Entity\ProApplicationUser
        personal: AppBundle\Doctrine\Entity\PersonalApplicationUser

    exclusion_policy: ALL
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineUserRepository

    embedded:
        userProfile:
            class: Wamcar\User\UserProfile
            columnPrefix: profile_

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        email:
            type: string
            length: 191   # needed to index field in utf8mb4
            unique: true
        facebookId:
            type: string
            length: 255
            nullable: true
        facebookAccessToken:
            type: string
            length: 255
            nullable: true
        linkedinId:
            type: string
            length: 255
            nullable: true
        linkedinAccessToken:
            type: string
            length: 255
            nullable: true
        googleId:
            type: string
            length: 255
            nullable: true
        googleAccessToken:
            type: string
            length: 255
            nullable: true

    oneToOne:
        avatar:
            targetEntity: AppBundle\Doctrine\Entity\UserPicture
            inversedBy: user
            joinColumn:
                name: avatar_id
                referencedColumnName: id
            cascade: ["persist", "merge", "remove"]

    oneToMany:
        conversationUsers:
            targetEntity: Wamcar\Conversation\ConversationUser
            mappedBy: user
            cascade: ["persist", "merge", "remove"]
        messages:
            targetEntity: Wamcar\Conversation\Message
            mappedBy: user
            cascade: ["persist", "merge", "remove"]
