Wamcar\User\ProjectVehicle:

    type: entity
    table: project_vehicle
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineProjectVehicleRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        make:
            type: string
        model:
            type: string
        yearMin:
            type: integer
            nullable: true
        mileageMax:
            type: integer
            nullable: true

    manyToOne:
        project:
            targetEntity: Wamcar\User\Project
            inversedBy: projectVehicles
            joinColumn:
                name: project_id
                referencedColumnName: id
