Wamcar\User\Lead:
  type: entity
  table: lead
  exclusion_policy: ALL
  repositoryClass: AppBundle\Doctrine\Repository\DoctrineLeadRepository

  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO

  fields:
    status:
      type: leadstatus
      nullable: false
    firstName:
      type: string
      nullable: false
    lastName:
      type: string
      nullable: true
    createdAt:
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: create
    lastContactedAt:
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: update
    nbPhoneAction:
      type: integer
      nullable: false
    nbPhoneProAction:
      type: integer
      nullable: false
    nbMessages:
      type: integer
      nullable: false
    nbLikes:
      type: integer
      nullable: false

  manyToOne:
    proUser:
      targetEntity: Wamcar\User\ProUser
      inversedBy: leads
      joinColumn:
        name: pro_user_id
        referencedColumnName: id
        nullable: false
    userLead:
      targetEntity: Wamcar\User\BaseUser
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: true

  oneToMany:
    saleDeclarations:
      targetEntity: Wamcar\Sale\Declaration
      mappedBy: leadBuyer
      cascade: ["persist", "merge", "remove"]