Wamcar\User\PersonalUser:
    type: entity

    oneToMany:
        vehicles:
            targetEntity: Wamcar\Vehicle\PersonalVehicle
            mappedBy: owner
            cascade: ["persist", "merge", "remove"]
        userConversations:
            targetEntity: Wamcar\Conversation\ConversationUser
            mappedBy: user
            cascade: ["persist", "merge", "remove"]
    oneToOne:
        project:
            targetEntity: Wamcar\User\Project
            mappedBy: personalUser
            cascade: ["persist"]
