Wamcar\User\User:

    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        basic: Wamcar\User\User
        application: AppBundle\Doctrine\Entity\ApplicationUser

    exclusion_policy: ALL
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineUserRepository

    embedded:
        userProfile:
            class: Wamcar\User\UserProfile

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        email:
            type: string
            length: 191   # needed to index field in utf8mb4
            unique: true
