Wamcar\User\PersonalUser:
    type: entity

    fields:
        orientation:
            type: personalorientation
            nullable: true
        contactAvailabilities:
            type: json
            nullable: true

    oneToMany:
        vehicles:
            targetEntity: Wamcar\Vehicle\PersonalVehicle
            mappedBy: owner
            cascade: ["persist", "merge", "remove"]
    oneToOne:
        project:
            targetEntity: Wamcar\User\Project
            mappedBy: personalUser
            cascade: ["persist", "remove"]