Wamcar\User\ProUser:
    type: entity

    fields:
        description:
            type: text
            nullable: true
        phonePro:
            type: string
            nullable: true

    oneToMany:
        garageMembers:
            targetEntity: Wamcar\Garage\GarageProUser
            mappedBy: proUser
            cascade: ["persist", "merge"]
