Wamcar\User\UserProfile:
    type: embeddable
    columnPrefix: profile_

    embedded:
        city:
            class: Wamcar\Location\City
            columnPrefix: city_
            nullable: true

    fields:
        title:
            type: usertitle
            nullable: true
        name:
            type: string
            nullable: true
        description:
            type: text
            nullable: true
        phone:
            type: string
            nullable: true
