Wamcar\User\ProUser:
    type: entity

    fields:
        phonePro:
            type: string
            nullable: true

    oneToMany:
        garageMemberships:
            targetEntity: Wamcar\Garage\GarageProUser
            mappedBy: proUser
            cascade: ["persist", "merge"]
        userConversations:
            targetEntity: Wamcar\Conversation\ConversationUser
            mappedBy: user
            cascade: ["persist", "merge", "remove"]
