Wamcar\User\ProUser:
    type: entity

    fields:
        slug:
            type: string
            length: 512
            gedmo:
                slug:
                    unique: true
                    separator: -
                    style: default
                    updatable: false
                    fields:
                        - userProfile.firstName
                        - userProfile.lastName
        phonePro:
            type: string
            nullable: true
        presentationTitle:
            type: string
            length: 50
            nullable: true
        landingPosition:
            type: integer
            nullable: true

    oneToMany:
        garageMemberships:
            targetEntity: Wamcar\Garage\GarageProUser
            mappedBy: proUser
            cascade: ["persist", "merge"]
        vehicles:
            targetEntity: Wamcar\Vehicle\ProVehicle
            mappedBy: seller
            cascade: ["persist", "merge", "remove"]
        leads:
            targetEntity: Wamcar\User\Lead
            mappedBy: proUser
            cascade: ["persist", "merge", "remove"]