Wamcar\User\ProLikeVehicle:
    type: entity

    manyToOne:
        vehicle:
            targetEntity: Wamcar\Vehicle\ProVehicle
            inversedBy: likes
            joinColumn:
                name: vehicle_id
                referencedColumnName: id
                nullable: false