Wamcar\Vehicle\PersonalVehicle:

    type: entity
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineVehicleRepository

    exclusion_policy: ALL

    id:
        id:
            type: uuid

    oneToMany:
        pictures:
            targetEntity: AppBundle\Doctrine\Entity\VehiclePicture
            mappedBy: vehicle
            cascade: ["persist", "merge"]

    embedded:
        registration:
            class: Wamcar\Vehicle\Registration
        modelVersion:
            class: Wamcar\Vehicle\ModelVersion

    fields:
        transmission:
            type: vehicletransmission
        safetyTest:
            type: vehicletransmission
            nullable: true
        maintenanceState:
            type: vehicletransmission
            nullable: true
        registrationDate:
            type: date_immutable
        bodyState:
            type: integer
        engineState:
            type: integer
            nullable: true
        tyreState:
            type: integer
            nullable: true
        isTimingBeltChanged:
            type: boolean
            nullable: true
        isImported:
            type: boolean
            nullable: true
        isFirstHand:
            type: boolean
            nullable: true
        additionalInformation:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
