Wamcar\Vehicle\ModelVersion:

    type: embeddable
    columnPrefix: version_

    fields:
        name:
            type: string
            nullable: true

    embedded:
        engine:
            class: Wamcar\Vehicle\Engine
        model:
            class: Wamcar\Vehicle\Model
