Wamcar\Vehicle\ProVehicle:

    type: entity
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineProVehicleRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false

    exclusion_policy: ALL

    id:
        id:
            type: uuid

    oneToMany:
        pictures:
            targetEntity: AppBundle\Doctrine\Entity\ProVehiclePicture
            mappedBy: vehicle
            cascade: ["persist", "merge"]

    manyToOne:
        garage:
            targetEntity: Wamcar\Garage\Garage
            inversedBy: proVehicles
            joinColumn:
                name: garage_id
                referencedColumnName: id

    embedded:
        registration:
            class: Wamcar\Vehicle\Registration
        modelVersion:
            class: Wamcar\Vehicle\ModelVersion
        city:
            class: Wamcar\Location\City
            columnPrefix: city_

    fields:
        transmission:
            type: vehicletransmission
        safetyTestState:
            type: vehiclesafetyteststate
        safetyTestDate:
            type: vehiclesafetytestdate
        maintenanceState:
            type: vehiclemaintenancestate
        registrationDate:
            type: date
        mileage:
            type: integer
        bodyState:
            type: integer
        engineState:
            type: integer
            nullable: true
        tyreState:
            type: integer
            nullable: true
        isTimingBeltChanged:
            type: boolean
            nullable: true
        isImported:
            type: boolean
            nullable: true
        isFirstHand:
            type: boolean
            nullable: true
        additionalInformation:
            type: text
            nullable: true
        price:
            type: float
            nullable: false
        catalogPrice:
            type: float
            nullable: true
        discount:
            type: float
            nullable: true
        guarantee:
            type: string
            nullable: true
        otherGuarantee:
            type: string
            nullable: true
        funding:
            type: string
            nullable: true
        otherFunding:
            type: string
            nullable: true
        additionalServices:
            type: text
            nullable: true
        reference:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: date
            nullable: true
