Wamcar\Vehicle\ProVehicle:

    type: entity
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineProVehicleRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false

    exclusion_policy: ALL

    id:
        id:
            type: uuid
    entityListeners:
        AppBundle\EntityListener\VehicleListener:

    oneToMany:
        pictures:
            targetEntity: AppBundle\Doctrine\Entity\ProVehiclePicture
            mappedBy: vehicle
            cascade: ["persist", "merge", "remove"]
            orphanRemoval: true
            orderBy:
                position: ASC

        headerMessages:
            targetEntity: Wamcar\Conversation\Message
            mappedBy: proVehicleHeader
            cascade: ["persist", "merge", "remove"]
            orphanRemoval: true

        messages:
            targetEntity: Wamcar\Conversation\Message
            mappedBy: proVehicle
            cascade: ["persist", "merge", "remove"]
            orphanRemoval: true
        likes:
            targetEntity: Wamcar\User\ProLikeVehicle
            mappedBy: vehicle
            cascade: ["persist", "merge", "remove"]
            orderBy:
              updatedAt: DESC

    manyToOne:
        garage:
            targetEntity: Wamcar\Garage\Garage
            inversedBy: proVehicles
            joinColumn:
                name: garage_id
                referencedColumnName: id
        seller:
            targetEntity: Wamcar\User\ProUser
            inversedBy: vehicles
            joinColumn:
                name: seller_id
                referencedColumnName: id
                nullable: false

    embedded:
        registration:
            class: Wamcar\Vehicle\Registration
        modelVersion:
            class: Wamcar\Vehicle\ModelVersion
        city:
            class: Wamcar\Location\City
            columnPrefix: city_

    fields:
        transmission:
            type: vehicletransmission
        safetyTestState:
            type: vehiclesafetyteststate
            nullable: true
        safetyTestDate:
            type: date
            nullable: true
        maintenanceState:
            type: vehiclemaintenancestate
            nullable: true
        registrationDate:
            type: date
        isUsed:
            type: boolean
        isUsedSlugValue:
            type: string
        mileage:
            type: integer
        bodyState:
            type: integer
            nullable: true
        engineState:
            type: integer
            nullable: true
        tyreState:
            type: integer
            nullable: true
        timingBeltState:
            type: vehicletimingbeltstate
            nullable: true
        isImported:
            type: boolean
            nullable: true
        isFirstHand:
            type: boolean
            nullable: true
        additionalInformation:
            type: text
            nullable: true
        price:
            type: float
            nullable: false
        catalogPrice:
            type: float
            nullable: true
        discount:
            type: float
            nullable: true
        guarantee:
            type: vehicleguarantee
            nullable: true
        otherGuarantee:
            type: string
            nullable: true
        funding:
            type: vehiclefunding
            nullable: true
        otherFunding:
            type: string
            nullable: true
        additionalServices:
            type: text
            nullable: true
        reference:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: date
            nullable: true
        slug:
            type: string
            length: 512
            gedmo:
                slug:
                    unique: true
                    separator: -
                    style: default
                    updatable: false
                    handlers:
                        Gedmo\Sluggable\Handler\RelativeSlugHandler:
                            relationField: garage
                            relationSlugField: address.city.name
                            separator: -
                            urilize: true
                    fields:
                        - modelVersion.model.make.name
                        - modelVersion.model.name
                        - isUsedSlugValue
