services:

    AppBundle\Form\Builder\:
        resource: '../../../Form/Builder'
        public: false
        autowire: true
        autoconfigure: false

    AppBundle\Elasticsearch\Builder\:
        resource: '../../../Elasticsearch/Builder'
        public: true
        autowire: true
        autoconfigure: false
