services:

    AppBundle\Controller\Front\BaseController:
        abstract: true
        calls:
            - ['setTemplatingEngine', ['@templating']]
            - ['setRouter', ['@router']]
            - ['setSession', ['@session']]
            - ['setTokenStorage', ['@security.token_storage']]
            - ['setAuthorizationChecker', ['@security.authorization_checker']]

    AppBundle\Controller\Front\AdministrationContext\BackendController:
        calls:
            - ['setGarageEditionService', ['@AppBundle\Services\Garage\GarageEditionService']]

    AppBundle\Controller\Front\:
        resource: '../../../Controller/Front'
        exclude: '../../../Controller/Front/{BaseController.php,AdministrationContext/BackendController.php}'
        public: false
        autowire: true
        autoconfigure: false
        parent: AppBundle\Controller\Front\BaseController
        tags: ['controller.service_arguments']


    AppBundle\Controller\Front\SecurityController:
        parent: AppBundle\Controller\Front\BaseController
        autowire: true
        arguments:
            - '@form.factory'
            - '@AppBundle\Security\UserRegistrationService'
            - '@AppBundle\Security\UserAuthenticator'
            - '@AppBundle\Services\User\UserEditionService'
            - '@AppBundle\Doctrine\Repository\DoctrineUserRepository'
            - '@AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository'
            - '@AppBundle\Services\User\UserGlobalSearchService'
            - '@security.authentication_utils'
            - '@simple_bus.event_bus'
            - '@hwi_oauth.security.oauth_utils'
            - '%hwi_oauth.firewall_names%'
            - '%hwi_oauth.target_path_parameter%'
            - '%hwi_oauth.failed_use_referer%'
            - '%hwi_oauth.use_referer%'


    AppBundle\Controller\Api\BaseController:
        abstract: true
        calls:
            - ['setRouter', ['@router']]
            - ['setSession', ['@session']]

    AppBundle\Controller\Api\:
        resource: '../../../Controller/Api'
        exclude: '../../../Controller/Api/BaseController.php'
        public: false
        autowire: true
        autoconfigure: false
        parent: AppBundle\Controller\Api\BaseController
        tags: ['controller.service_arguments']
