services:
    wamcar.event.mail.abstract_event_handler:
        abstract: true
        class: AppBundle\MailWorkflow\AbstractEmailEventHandler
        arguments:
          - '@wamcar.mail_workflow.mailer'
          - '@router'
          - '@templating'
          - '@translator'

    wamcar.event.notifications.abstract_event_handler:
        abstract: true
        class: AppBundle\Notifications\AbstractNotificationsHandler
        arguments:
          - '@mgilet.notification'
          - '@router'

    wamcar.event.password_reset_token_generated:
        parent: wamcar.event.mail.abstract_event_handler
        class: AppBundle\MailWorkflow\NotifyUserOfPasswordResetTokenGenerated
        arguments:
          - password_reset_token_generated
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\User\Event\UserPasswordResetTokenGenerated, method: notify }

    wamcar.event.registration_token_generated:
        parent: wamcar.event.mail.abstract_event_handler
        class: AppBundle\MailWorkflow\NotifyUserOfRegistrationTokenGenerated
        arguments:
          - registration_token_generated
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\User\Event\UserCreated, method: notify }

    wamcar.event.registration_pro:
        parent: wamcar.event.mail.abstract_event_handler
        class: AppBundle\MailWorkflow\NotifyProUserOfRegistration
        arguments:
          - registration_pro
          - '%admin_email%'
          - '%admin_name%'
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\User\Event\ProUserCreated, method: notify }

    wamcar.event.vehicle_updated:
        class: Wamcar\Vehicle\Event\ResolveLiipImagineCache
        arguments:
           - '@AppBundle\Services\Picture\PathVehiclePicture'
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\VehicleCreated, method: notify }
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\PersonalVehicleCreated, method: notify }
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\ProVehicleCreated, method: notify }
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\VehicleUpdated, method: notify }
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\PersonalVehicleUpdated, method: notify }
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\ProVehicleUpdated, method: notify }

    wamcar.event.vehicle_removed:
        parent: wamcar.event.mail.abstract_event_handler
        class: AppBundle\MailWorkflow\NotifyOwnerOfVehicleRemoved
        arguments:
           - vehicle_removed
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\PersonalVehicleRemoved, method: notify }

    wamcar.event.elasticsearch.personal_user_updated.index:
        class: AppBundle\Elasticsearch\IndexUpdatedPersonalUser
        autowire: true
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\User\Event\PersonalUserUpdated, method: notify }

    wamcar.event.elasticsearch.personal_project_updated.index:
            class: AppBundle\Elasticsearch\IndexUpdatedPersonalProject
            autowire: true
            tags:
                - { name: event_subscriber, subscribes_to: \Wamcar\User\Event\PersonalProjectUpdated, method: notify }


    wamcar.event.elasticsearch.garage_updated.index:
        class: AppBundle\Elasticsearch\IndexUpdatedGarage
        autowire: true
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Garage\Event\GarageUpdated, method: notify }

    wamcar.event.elasticsearch.pro_vehicle_created.index:
        class: AppBundle\Elasticsearch\IndexCreatedProVehicle
        autowire: true
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\ProVehicleCreated, method: notify }

    wamcar.event.elasticsearch.pro_vehicle_updated.index:
        class: AppBundle\Elasticsearch\IndexUpdatedProVehicle
        autowire: true
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\ProVehicleUpdated, method: notify }
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\ProVehicleRemoved, method: notify }

    wamcar.event.elasticsearch.personal_vehicle_created.index:
        class: AppBundle\Elasticsearch\IndexCreatedPersonalVehicle
        autowire: true
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\PersonalVehicleCreated, method: notify }

    wamcar.event.elasticsearch.personal_vehicle_updated.index:
        class: AppBundle\Elasticsearch\IndexUpdatedPersonalVehicle
        autowire: true
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\PersonalVehicleUpdated, method: notify }
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\PersonalVehicleRemoved, method: notify }

    wamcar.event.adding_pictures_to_vehicle_notification:
        parent: wamcar.event.mail.abstract_event_handler
        class: AppBundle\MailWorkflow\NotifyUserOfAddingPicturesToVehicle
        arguments:
          - sell.adding_pictures_to_vehicle_notification
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Vehicle\Event\AddingPicturesToVehicleNotification, method: notify }

    wamcar.event.message_created:
        parent: wamcar.event.mail.abstract_event_handler
        class: AppBundle\MailWorkflow\NotifyUserOfMessageCreated
        arguments:
          - message_created
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\Conversation\Event\MessageCreated, method: notify }

    wamcar.event.user_like_vehicle:
        parent: wamcar.event.notifications.abstract_event_handler
        class: AppBundle\Notifications\LikeNotificationsHandler
        tags:
            - { name: event_subscriber, subscribes_to: \Wamcar\User\Event\UserLikeVehicleEvent, method: notify }

    googleApi.event.place_detail_error:
        parent: wamcar.event.mail.abstract_event_handler
        class: AppBundle\MailWorkflow\NotifyAdminOfGoogleApiReturnError
        arguments:
          $type: place_detail_error
        tags:
            - { name: event_subscriber, subscribes_to: \GoogleApi\Event\PlaceDetailError, method: notify }
