services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    AppBundle\Twig\PictureExtension:
        class: 'AppBundle\Twig\PictureExtension'
        tags:
            - { name: twig.extension }
        arguments:
          - '@vich_uploader.templating.helper.uploader_helper'
          - '%placeholders%'
          - '@AppBundle\Services\Picture\PathVehiclePicture'
          - '@AppBundle\Services\Picture\PathGaragePicture'
          - '@AppBundle\Services\Picture\PathUserPicture'

    AppBundle\Twig\StarsExtension:
        class: 'AppBundle\Twig\StarsExtension'
        tags:
            - { name: twig.extension }

    AppBundle\Twig\ConversationExtension:
        class: 'AppBundle\Twig\ConversationExtension'
        tags:
            - { name: twig.extension }
        autowire: true

    AppBundle\Twig\TestsExtension:
        class: 'AppBundle\Twig\TestsExtension'
        tags:
            - { name: twig.extension }
        autowire: true

    AppBundle\Twig\NotificationPlusExtension:
        tags:
            - { name: twig.extension }
        autowire: true

    AppBundle\Twig\URLFactoryExtension:
        class: 'AppBundle\Twig\URLFactoryExtension'
        autowire: true
        tags:
            - { name: twig.extension }

    AppBundle\Twig\RadarChartExtension:
        class: 'AppBundle\Twig\RadarChartExtension'
        autowire: true
        tags:
            - { name: twig.extension }

    AppBundle\Twig\SaleStatusExtension:
        class: 'AppBundle\Twig\SaleStatusExtension'
        autowire: true
        tags:
            - { name: twig.extension }