services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  AppBundle\Twig\ConversationExtension:
    tags:
      - { name: twig.extension }
    autowire: true

  AppBundle\Twig\FormExtension:
    tags:
      - { name: twig.extension }

  AppBundle\Twig\FormatExtension:
    tags:
      - { name: twig.extension }

  AppBundle\Twig\JsonExtension:
    tags:
      - { name: twig.extension }
    autowire: true

  AppBundle\Twig\NotificationPlusExtension:
    tags:
      - { name: twig.extension }
    autowire: true

  AppBundle\Twig\PictureExtension:
    tags:
      - { name: twig.extension }
    arguments:
      - '@vich_uploader.templating.helper.uploader_helper'
      - '%placeholders%'
      - '@AppBundle\Services\Picture\PathVehiclePicture'
      - '@AppBundle\Services\Picture\PathGaragePicture'
      - '@AppBundle\Services\Picture\PathUserPicture'
      - '@AppBundle\Services\Picture\PathUserBanner'

  AppBundle\Twig\RadarChartExtension:
    autowire: true
    tags:
      - { name: twig.extension }

  AppBundle\Twig\StarsExtension:
    tags:
      - { name: twig.extension }

  AppBundle\Twig\TestsExtension:
    autowire: true
    tags:
      - { name: twig.extension }

  AppBundle\Twig\TrackingExtension:
    tags:
      - { name: twig.extension }

  AppBundle\Twig\URLFactoryExtension:
    autowire: true
    tags:
      - { name: twig.extension }