services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Form\Type\:
        resource: '../../../Form/Type'
        exclude: '../../../Form/Type/{VehicleType,VehicleInformationType}.php'
