services:
    GoogleApi\GoogleMapsApiConnector:
        autowire: true
        autoconfigure: true
        public: false
        arguments:
          - '@event_bus'
          - '@logger'
          - '%env(GOOGLE_MAPS_API_HOST)%'
          - '%env(GOOGLE_API_SERVER_KEY)%'
          - '%env(GOOGLE_MAPS_API_PLACE_DETAILS_PATH)%'

