services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GoogleApi\:
    resource: '../../../../GoogleApi/'

  GoogleApi\GoogleMapsApiConnector:
    arguments:
      - '@event_bus'
      - '@logger'
      - '%env(GOOGLE_MAPS_API_HOST)%'
      - '%env(GOOGLE_API_SERVER_KEY)%'
      - '%env(GOOGLE_MAPS_API_PLACE_DETAILS_PATH)%'

  GoogleApi\GAReportingAPIService:
    arguments:
      $router: '@router'
      $applicationName: '%sitename%'
      $viewId: '%env(GOOGLE_ANALYTICS_VIEW_ID)%'

  GoogleApi\GoogleYoutubeApiService:
    arguments:
      $applicationName: '%sitename%'


  GoogleApi\GoogleRecaptchaService:
    arguments:
      - '%env(GOOGLE_RECAPTCHA_VERIFY_URL)%'
      - '%env(GOOGLE_RECAPTCHA_SECRET)%'

  GoogleApi\GoogleCloudStorageService:
    arguments:
      $keyFilePath: '%env(GOOGLE_APPLICATION_CREDENTIALS)%'
      $bucketnamePrefix: '%google.storage.bucketname.prefix%'
      $namer: '@Vich\UploaderBundle\Naming\SmartUniqueNamer'
