services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\EntityListener\VehicleListener:
        tags:
            - { name: doctrine.orm.entity_listener }
