services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\EntityListener\VehicleListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    AppBundle\EventListener\AnnotationListener:
        arguments: ['@annotation_reader']
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    AppBundle\EventListener\SitemapSubscriber:
        tags:
            - { name: kernel.event_subscriber, priority: 100 }