services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    Wamcar\Vehicle\ProVehicleRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineProVehicleRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: [ 'Wamcar\Vehicle\ProVehicle' ]

    Wamcar\Vehicle\PersonalVehicleRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrinePersonalVehicleRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: [ 'Wamcar\Vehicle\PersonalVehicle' ]

    # Interfaces default service
    Wamcar\User\UserRepository: '@AppBundle\Doctrine\Repository\DoctrineUserRepository'

    AppBundle\Doctrine\Repository\DoctrineUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\User\BaseUser']

    AppBundle\Doctrine\Repository\DoctrineProUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineProUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Doctrine\Entity\ProApplicationUser']

    AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Doctrine\Entity\PersonalApplicationUser']

    AppBundle\Doctrine\Repository\DoctrineGarageRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineGarageRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\Garage\Garage']

    AppBundle\Doctrine\Repository\DoctrineGarageProUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineGarageProUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\Garage\GarageProUser']
