services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    # Même sans public est accessible via les commands
    Wamcar\Vehicle\ProVehicleRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineProVehicleRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: [ 'Wamcar\Vehicle\ProVehicle' ]
        public: true

    Wamcar\Vehicle\PersonalVehicleRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrinePersonalVehicleRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: [ 'Wamcar\Vehicle\PersonalVehicle' ]
        public: true

    # Interfaces default service
    Wamcar\User\UserRepository: '@AppBundle\Doctrine\Repository\DoctrineUserRepository'

    AppBundle\Doctrine\Repository\DoctrineUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\User\BaseUser']

    AppBundle\Doctrine\Repository\DoctrineProUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineProUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Doctrine\Entity\ProApplicationUser']

    AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Doctrine\Entity\PersonalApplicationUser']

    AppBundle\Doctrine\Repository\DoctrineGarageRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineGarageRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\Garage\Garage']

    AppBundle\Doctrine\Repository\DoctrineGarageProUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineGarageProUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\Garage\GarageProUser']

    AppBundle\Doctrine\Repository\DoctrineProjectRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineProjectRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\User\Project']

    AppBundle\Doctrine\Repository\DoctrineProjectVehicleRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineProjectVehicleRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\User\ProjectVehicle']

    AppBundle\Doctrine\Repository\DoctrineConversationRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineConversationRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Doctrine\Entity\ApplicationConversation']

    AppBundle\Doctrine\Repository\DoctrineConversationUserRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineConversationUserRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\Conversation\ConversationUser']

    AppBundle\Doctrine\Repository\DoctrineMessageRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineMessageRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['Wamcar\Conversation\Message']

    AppBundle\Doctrine\Repository\DoctrineCityRepository:
        class: 'AppBundle\Doctrine\Repository\DoctrineCityRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Doctrine\Entity\ApplicationCity']
        public: true
