services:

    AppBundle\Session\ConversationSession:
        resource: '%kernel.project_dir%/src/AppBundle/Session/ConversationSession'
        public: false
        autowire: true
        autoconfigure: false
