imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: front_mock.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    placeholders:
        avatar: '/assets/images/placeholders/user/user.png'
        banner: '/assets/images/placeholders/garages/garage-760x340.jpg'
        logo: '/assets/images/placeholders/garages/logo-toyota.png'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_name: 'Wamcar'
        facebook_url: 'https://www.facebook.com/wamcar.france/'
        twitter_url: 'https://twitter.com/wamcar'
        inte: '%inte%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%env(MYSQL_HOST)%'
        port: '%env(MYSQL_PORT)%'
        dbname: '%env(MYSQL_DATABASE)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASSWORD)%'
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            usertitle:  AppBundle\Doctrine\Type\UserTitleType
            vehicletransmission:  AppBundle\Doctrine\Type\VehicleTransmissionType
            vehiclemaintenancestate:  AppBundle\Doctrine\Type\VehicleMaintenanceStateType
            vehiclesafetyteststate:  AppBundle\Doctrine\Type\VehicleSafetyTestStateType
            vehiclesafetytestdate:  AppBundle\Doctrine\Type\VehicleSafetyTestDateType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        filters:
            softDeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            Wamcar:
                type: yml
                dir: '%kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/Wamcar'
                is_bundle: false
                prefix: Wamcar
                alias: Wamcar
            AppBundle:
                type: yml
                dir: '%kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/AppBundle'
                is_bundle: false
                prefix: AppBundle
                alias: AppBundle

doctrine_migrations:
    dir_name:             '%kernel.root_dir%/../database/migrations'
    namespace:            Application\Migrations
    table_name:           migration_versions

# Swiftmailer Configuration
swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    host: '%env(MAILER_HOST)%'
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASSWORD)%'
    port:      "%env(MAILER_PORT)%"
    encryption: tls
    spool: { type: memory }

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            softdeleteable: true
            timestampable: true
            blameable: true

vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: false
        directories:
            - {path: '%kernel.root_dir%/../src/AppBundle/Resources/config/uploader'}
    mappings:
        vehicle_image:
            uri_prefix:         /uploads/images/vehicles
            upload_destination: '%env(UPLOAD_DIR)%/images/vehicles'
            namer:              vich_uploader.namer_hash
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 3, dirs: 2}
            inject_on_load:     true
        user_image:
            uri_prefix:         /uploads/images/users
            upload_destination: '%env(UPLOAD_DIR)%/images/users'
            namer:              vich_uploader.namer_hash
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 3, dirs: 2}
            inject_on_load:     true
        garage_banner:
            uri_prefix:         /uploads/images/garages/banner
            upload_destination: '%env(UPLOAD_DIR)%/images/garages/banner'
            namer:              vich_uploader.namer_hash
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 3, dirs: 2}
            inject_on_load:     true
        garage_logo:
            uri_prefix:         /uploads/images/garages/logo
            upload_destination: '%env(UPLOAD_DIR)%/images/garages/logo'
            namer:              vich_uploader.namer_hash
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 3, dirs: 2}
            inject_on_load:     true

liip_imagine:
    loaders:
        uploaded_files:
            filesystem:
                data_root: '%env(IMAGINE_FILESYSTEM_ROOT)%'
    data_loader: uploaded_files


    # your filter sets are defined here
    filter_sets:
        cache: ~
        vehicle_picture:
            quality: 75
            filters:
                thumbnail: { size: [800, 500] }
        vehicle_mini_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        vehicle_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [260, 163], mode: outbound }
