imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            channels: ['!doctrine', '!user_provider']
        user_provider:
            type: stream
            path: '%kernel.logs_dir%/user_provider_%kernel.environment%.log'
            channels: user_provider
        doctrine:
            type: stream
            path: '%kernel.logs_dir%/doctrine_%kernel.environment%.log'
            channels: doctrine
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
