imports:
    - { resource: parameters.yml }
    - { resource: "parameters_inte.yml" }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_name: '%site_name%'
        site_url_no_protocol: '%site_url_no_protocol%'
        site_url_no_subdomain: '%site_url_no_subdomain%'
        site_url: '%site_url%'
        inte: '%inte%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%env(MYSQL_HOST)%'
        port: '%env(MYSQL_PORT)%'
        dbname: '%env(MYSQL_DATABASE)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASSWORD)%'
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        filters:
            softDeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            Wamcar:
                type: yml
                dir: '%kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/Wamcar'
                is_bundle: false
                prefix: Wamcar
                alias: Wamcar
            AppBundle:
                type: yml
                dir: '%kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/AppBundle'
                is_bundle: false
                prefix: AppBundle
                alias: AppBundle

doctrine_migrations:
    dir_name:             '%kernel.root_dir%/../database/migrations'
    namespace:            Application\Migrations
    table_name:           migration_versions

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            softdeleteable: true
            timestampable: true
            blameable: true
