easy_admin:
  site_name: 'Wamcar Backend'
  design:
    brand_color: '#cc4b37'
    color_scheme: 'light'
    menu:
      - { label: "Tableau d'administration", route: 'admin_board' }
      - { label: 'Ressources :' }
      - Garage
      - ProApplicationUser
      - PersonalApplicationUser
      - CronJobs
  formats:
    date: 'd/m/Y'
    datetime: 'd/m/Y H:i:s'
  list:
    actions:
      - { name: 'search', icon: 'search', label: false, title: 'Rechercher' }
      - { name: 'edit', icon: 'edit', label: false, title: 'Editer' }
      - { name: 'show', icon: 'eye', label: false, title: 'Voir'}
      - { name: 'delete', icon: 'trash', label: false, title: 'Supprimer' }
      - { name: '-new' } # Creation is not allow in backend
  entities:
    Garage:
      class: Wamcar\Garage\Garage
      list:
        max_results: 30
        fields:
          - { property: 'id', label: 'ID'}
          - { property: 'name', label: 'Nom'}
          - { property: 'mainAdministrator.Id', label: 'Gest. Id'}
          - { property: 'mainAdministrator.fullName', label: 'Gest. Nom'}
          - googlePlaceId
          - googleRating
          - polevoId
          - { property: 'optionAdminSellers', label: 'Gest. vend.'}
          - { property: 'optionAdminVisible', label: 'Gest. visible'}
          - { property: 'countProVehicles', label: '#Vhl.'}
          - { property: 'countMembers', label: '#Memb.'}
          - { property: 'deletedAt', label: 'Suppr.' }
        actions:
          - { name: 'viewGaragePage', icon: 'file',  label: false, title: 'Page Garage', target: '_black' }
          - { name: 'edit', icon: 'map-marker', label: false, title: 'Editer' }
          - { name: 'front_garage_edit', type: 'route', icon: 'edit', label: false, title: 'Formulaire Wamcar', target: '_blank'}
      show:
        fields:
          - id
          - name
          - slug
          - googlePlaceId
          - googleRating
          - siren
          - apiClientId
          - apiSecret
          - polevoId
          - phone
          - { property: 'email', type: 'email'}
          - openingHours
          - presentation
          - benefit
          - { property: 'address.fullAddress', label: 'Adr.'}
          - { property: 'optionAdminSellers', label: 'Gest. vendeur'}
          - { property: 'countProVehicles', label: '#Vhl.'}
          - members

      form:
        help: >
          Merci d'utiliser le formulaire Wamcar qui vous permet de modifier les informations du garage.<br>
          Ce formulaire ne doit être utilisé QUE pour supprimer le GooglePlaceId et le GoogleRating  car le formulaire
          n'est pas relié à l'API Google pour récupérer les informations automatiquement.<br>
          De plus, si le GooglePlaceId, le nom et/ou le SIREN sont déjà existants Alors vous aurez une erreur interne
          lors de la validation. Faire précédente et modifier alors votre saisie.
        fields:
          - { property: 'id', type_options: { disabled: 'disabled' } }
          - { property: 'googlePlaceId'}
          - { property: 'googleRating'}
          - { property: 'name'}
          - { property: 'siren'}
          - { property: 'polevoId'}
          - { property: 'optionAdminSellers', label: 'Gest. vend.'}
          - { property: 'optionAdminVisible', label: 'Gest. visible'}
    ProApplicationUser:
      class: AppBundle\Doctrine\Entity\ProApplicationUser
      label: 'Conseillers automobile'
      list:
        title: 'Conseillers automobile'
        max_results: 30
        fields:
          - id
          - { property: 'fullName', label: 'Prénom Nom' }
          - { property: 'email', label: 'E-mail', type: 'email' }
          - { property: 'slug'}
          - { property: 'apiClientId'}
          - { property: 'landingPosition', label: 'HP-pos.' }
          - { property: 'countVehicles', label: '#Vhl.'}
          - { property: 'numberOfGarages', label: '#Garages.'}
          - { property: 'createdAt', label: 'Insc.', type: 'date' }
          - { property: 'deletedAt', label: 'Suppr.', type: 'date' }
        sort: ['id', 'DESC']
        actions:
          - { name: 'editUserProfile', icon: 'pencil',  label: false, title: 'Editer Profil Wamcar', target: '_blank' }
          - { name: 'viewUserProfile', icon: 'user',  label: false, title: 'Voir Profil Wamcar', target: '_blank' }
          - { name: 'viewProUserPerformances', icon: 'euro',  label: false, title: 'Perf. vendeur', target: '_blank' }
      form:
        fields:
          - { property: 'id', type_options: { disabled: 'disabled' } }
          - { property: 'email', type: 'email', label: 'Login' }
          - { property: 'slug'}
          - { property: 'presentationTitle' }
          - { property: 'description'}
          - { property: 'landingPosition', label: 'HP-mixte-position'}
          - { property: 'youtubeVideoId' }
          - { property: 'videoShortText', type: 'fos_ckeditor', type_options: { config_name: 'easyadmin_config' } }
          - { property: 'videoText', type: 'fos_ckeditor', type_options: { config_name: 'easyadmin_config' } }
          - { property: 'appointmentText'}
          - { property: 'appointmentAutofillMessage'}
      show:
        fields:
          - id
          - slug
          - email
          - userProfile.title
          - userProfile.firstName
          - userProfile.lastName
          - userProfile.description
          - userProfile.phone
          - phonePro
          - { property: 'avatar.fileName' }
          - youtubeVideoId
          - videoShortText
          - videoText
          - appointmentText
          - appointmentAutofillMessage
          - facebookId
          - facebookAccessToken
          - linkedinId
          - linkedinAccessToken
          - googleId
          - googleAccessToken
          - twitterId
          - twitterAccessToken
          - { property: 'firstContactPreference', type: 'text' }
          - { property: 'preferences.privateMessageEmailEnabled', type: 'boolean', label: 'Pref. Nouv. Mess.' }
          - { property: 'preferences.privateMessageEmailFrequency', type: 'text', label: 'Nouv. Mess. freq.' }
          - { property: 'preferences.likeEmailEnabled', type: 'boolean', label: 'Pref. like' }
          - { property: 'preferences.likeEmailFrequency', label: 'Like Freq.' }
          - { property: 'affinityAnswer.sumittedAt', type: 'date', labe: 'WamAff Soumis le:' }
          - { property: 'affinityAnswer.treatedAt', type: 'date', label: 'WamAff Traité le:' }
          - { property: 'orientation', type: 'text' }
          - { property: 'contactAvailabilities', type: 'string' }
          - deletedAt
          - deletionReason
          - vehicles
          - garageMemberships
    PersonalApplicationUser:
      class: AppBundle\Doctrine\Entity\PersonalApplicationUser
      label: 'Particuliers'
      list:
        title: 'Particuliers'
        max_results: 30
        fields:
          - id
          - { property: 'fullName', label: 'Prénom Nom' }
          - { property: 'email', label: 'E-mail', type: 'email' }
          - { property: 'slug' }
          - { property: 'countVehicles', label: '#Vhl.'}
          - { property: 'createdAt', label: 'Insc.' }
          - { property: 'deletedAt', label: 'Suppr.' }
        sort: ['id', 'DESC']
        actions:
          - { name: 'viewUserProfile', icon: 'user',  label: false, title: 'Voir Profil Wamcar', target: '_blank' }
          - { name: 'convertToProAccount', icon: 'user-secret', label: false, title: 'Convertir en Pro'}
      form:
        fields:
          - { property: 'id', type_options: { disabled: 'disabled' } }
          - { property: 'email', type: 'email', label: 'Login' }
          - { property: 'slug'}
          - { property: 'description', type: 'textarea' }
      show:
        fields:
          - id
          - slug
          - email
          - userProfile.title
          - userProfile.firstName
          - userProfile.lastName
          - userProfile.description
          - userProfile.phone
          - userProfile.city
          - { property: 'avatar.fileName' }
          - facebookId
          - facebookAccessToken
          - linkedinId
          - linkedinAccessToken
          - googleId
          - googleAccessToken
          - twitterId
          - twitterAccessToken
          - { property: 'firstContactPreference', type: 'text' }
          - { property: 'preferences.privateMessageEmailEnabled', type: 'boolean', label: 'Pref. Nouv. Mess.' }
          - { property: 'preferences.privateMessageEmailFrequency', type: 'text', label: 'Nouv. Mess. freq.' }
          - { property: 'preferences.likeEmailEnabled', type: 'boolean', label: 'Pref. like' }
          - { property: 'preferences.likeEmailFrequency', label: 'Like Freq.' }
          - { property: 'affinityAnswer.sumittedAt', type: 'date', labe: 'WamAff Soumis le:' }
          - { property: 'affinityAnswer.treatedAt', type: 'date', label: 'WamAff Traité le:' }
          - { property: 'orientation', type: 'text' }
          - { property: 'contactAvailabilities', type: 'string' }
          - deletedAt
          - deletionReason
          - vehicles
    CronJobs:
      translation_domain: 'JMoseCommandScheduler'
      class: JMose\CommandSchedulerBundle\Entity\ScheduledCommand
      list:
        title: "list.title"
        fields:
          - { property: 'id', label: 'ID' }
          - { property: 'name', label: 'detail.name' }
          - { property: 'command', label: 'detail.command' }
          - { property: 'arguments', label: 'detail.arguments' }
          - { property: 'lastExecution', label: 'detail.lastExecution' }
          - { property: 'lastReturncode', label: 'detail.lastReturnCode' }
          - { property: 'locked', label: 'detail.locked', type: boolean}
          - { property: 'priority', label: 'detail.priority' }
          - { property: 'disabled', label: 'detail.disabled' }
        actions:
          - { name: 'jmose_command_scheduler_action_execute', type: 'route', label: 'action.execute' }
          - { name: 'jmose_command_scheduler_action_unlock', type: 'route', label: 'action.unlock' }
          - { name: 'new' }
      form:
        fields:
          - { property: 'name', label: 'detail.name' }
          - { property: 'command', label: 'detail.command', type: 'JMose\CommandSchedulerBundle\Form\Type\CommandChoiceType' }
          - { property: 'arguments', label: 'detail.arguments' }
          - { property: 'cronExpression', label: 'detail.cronExpression' }
          - { property: 'priority', label: 'detail.priority' }
          - { property: 'disabled', label: 'detail.disabled' }
          - { property: 'logFile', label: 'detail.logFile' }
      new:
        fields:
          - { property: 'executeImmediately', label: 'detail.executeImmediately' }
