# This file contains data mock used for frontend in the production environment
# if a data can not be removed from this file, it means that there are feature that are available but not implemented yet.

parameters:
    inte:
        vehicle:
            "twingo-3":
                picture: "assets/images/placeholders/vehicle/vehicle-default.jpg"
                brand: "Renault"
                name: "Twingo III lorem ipsum bonjour"
                model: "1.0 SCe 70 BC Intens"
                years: "2016"
                km: "13 280 km"
                city: "Villeurbanne"
                price: "8 990 €"
            "golf-2-tdi":
                picture: "assets/images/placeholders/vehicle/vehicle-default.jpg"
                pictures:
                  primary:
                    - assets/images/placeholders/vehicle/primary-1.jpg
                    - assets/images/placeholders/vehicle/primary-2.jpg
                    - assets/images/placeholders/vehicle/primary-3.jpg
                    - assets/images/placeholders/vehicle/primary-4.jpg
                    - assets/images/placeholders/vehicle/primary-5.jpg
                    - assets/images/placeholders/vehicle/primary-6.jpg
                    - assets/images/placeholders/vehicle/primary-7.jpg
                  secondary:
                    - assets/images/placeholders/vehicle/secondary-1.jpg
                    - assets/images/placeholders/vehicle/secondary-2.jpg
                    - assets/images/placeholders/vehicle/secondary-3.jpg
                    - assets/images/placeholders/vehicle/secondary-4.jpg
                    - assets/images/placeholders/vehicle/secondary-5.jpg
                    - assets/images/placeholders/vehicle/secondary-6.jpg
                    - assets/images/placeholders/vehicle/secondary-7.jpg
                brand: "Volkswagen"
                seller: "Stéphane Richin"
                color: "Noir"
                name: "Golf"
                version: "III (2) 90 D-4D Tendance 5P"
                model: "2.0 TDI 184 BlueMotion Technology FAP GTD"
                years: "2014"
                km: "34 008 km"
                city: "Villefranche sur Saône"
                price: "17 125 €"
                description: >
                  <p>Lorem ipsum vel taciti Morbi Quisque pharetra ut volutpat fringilla erat, aliquet augue at felis elit. Curabitur ornare erat. Mi Etiam per porttitor laoreet, ullamcorper in sed, ante. Vitae. Ullamcorper. Lobortis sed Proin rutrum, Cras semper. Auctor scelerisque nunc ipsum Sed Donec in velit vitae. In mi erat, In augue.</p>
                  <p>Lorem ipsum finibus mollis per risus sollicitudin pulvinar ipsum Vestibulum faucibus sit elit. At volutpat imperdiet vitae dictum nisl. Fusce arcu Quisque velit egestas, dui ante. Ornare pharetra luctus vitae. At ultricies lobortis dolor. Luctus dolor. Consequat adipiscing Nam velit scelerisque lectus vitae fringilla lectus porttitor id ultrices sollicitudin iaculis. A sed id tempor turpis lectus. Ac eleifend vitae vestibulum pharetra in luctus ex, Donec felis a sed laoreet, tortor Donec ut lorem Quisque metus augue efficitur, velit felis mi.</p>
            "ds3":
                picture: "assets/images/placeholders/vehicle/vehicle-default.jpg"
                brand: "Citroën"
                name: "DS3"
                model: "120ch Sport Chic + nav"
                years: "2015"
                km: "16 700 km"
                city: "Oullins"
                price: "16 589 €"
        user:
          fullName: Stéphane Richin
          name: Richin
          firstName: Stéphane
          tel_fix: 04 99 98 97 96
          tel_mob: 06 85 84 82 81
          email: stephane@novaway.fr
          picture: /assets/images/placeholders/user/user.png
        garage:
          picture:
            small: assets/images/placeholders/garages/garage-360x160.jpg
            default: assets/images/placeholders/garages/garage-760x340.jpg
          logo: assets/images/placeholders/garages/logo-toyota.png
          name: Toyota Villeurbanne
          address: 3 avenue Emile Zola
          postal_code: 69100
          city: Villeurbanne
          schedule: Ouvert du lundi au samedi, de 9h à 12h et de 14h à 18h
          tel: 04 99 98 97 96
          presentation: >
            <p>Lorem ipsum ut ultrices molestie. Nec congue interdum, augue, laoreet, ad sit Curabitur neque massa maximus odio Quisque sagittis Morbi at Etiam faucibus vitae. Vel non nisi. Magna neque nibh. Cras Vestibulum vel volutpat, Curabitur Donec efficitur, pharetra efficitur, dapibus Suspendisse condimentum id Donec sed nibh id auctor eu quis, inceptos Quisque Class nisl. Sit ac, luctus vel felis risus.</p>
            <p>Lorem ipsum ut ultrices molestie. Nec congue interdum, augue, laoreet, ad sit Curabitur neque massa maximus odio Quisque sagittis Morbi at Etiam faucibus vitae. Vel non nisi. Magna neque nibh. Cras Vestibulum vel volutpat, Curabitur Donec efficitur, pharetra efficitur, dapibus Suspendisse condimentum id Donec sed nibh id auctor eu quis, inceptos Quisque Class nisl. Sit ac, luctus vel felis risus.</p>
          sellers:
            - stephane:
              picture: /assets/images/placeholders/user/user.png
              fullName: Stéphane Richin
            - elodie:
              picture: /assets/images/placeholders/user/user.png
              fullName: Elodie Santini
            - marc:
              picture: /assets/images/placeholders/user/user.png
              fullName: Marc Van Houtte
            - alexis:
              picture: /assets/images/placeholders/user/user.png
              fullName: Alexis Sanchez
