# This file contains data mock used for frontend in the production environment
# if a data can not be removed from this file, it means that there are feature that are available but not implemented yet.

parameters:
    inte:
        vehicle:
            "twingo-3":
                picture: "assets/images/placeholders/vehicle/vehicle-default.jpg"
                brand: "Renault"
                name: "Twingo III lorem ipsum bonjour"
                model: "1.0 SCe 70 BC Intens"
                years: "2016"
                km: "13 280 km"
                city: "Villeurbanne"
                price: "8 990 €"
            "golf-2-tdi":
                picture: "assets/images/placeholders/vehicle/vehicle-default.jpg"
                brand: "Volkswagen"
                name: "Golf"
                model: "2.0 TDI 184 BlueMotion Technology FAP GTD"
                years: "2014"
                km: "34 008 km"
                city: "Villefranche sur Saône"
                price: "17 125 €"
            "ds3":
                picture: "assets/images/placeholders/vehicle/vehicle-default.jpg"
                brand: "Citroën"
                name: "DS3"
                model: "120ch Sport Chic + nav"
                years: "2015"
                km: "16 700 km"
                city: "Oullins"
                price: "16 589 €"
        user:
          fullName: Stéphane Richin
          name: Richin
          firstName: Stéphane
          tel_fix: 04 99 98 97 96
          tel_mob: 06 85 84 82 81
          email: stephane@novaway.fr
          picture: /assets/images/placeholders/user/user.png
        garage:
          picture:
            small: assets/images/placeholders/garages/garage-360x160.jpg
            default: assets/images/placeholders/garages/garage-760x340.jpg
          logo: assets/images/placeholders/garages/logo-toyota.png
          name: Toyota Villeurbanne
          address: 3 avenue Emile Zola, 69100 Villeurbanne
          schedule: Ouvert du lundi au samedi, de 9h à 12h et de 14h à 18h
          tel: 04 99 98 97 96
          sellers:
            - stephane:
              picture: /assets/images/placeholders/user/user.png
              name: Stéphane Richin
            - elodie:
              picture: /assets/images/placeholders/user/user.png
              name: Elodie Santini
            - marc:
              picture: /assets/images/placeholders/user/user.png
              name: Marc Van Houtte
            - alexis:
              picture: /assets/images/placeholders/user/user.png
              name: Alexis Sanchez
