security:

    encoders:
            Wamcar\User\ProUser: bcrypt
            Wamcar\User\PersonalUser: bcrypt

    providers:
        in_memory:
            memory: ~


    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        front:
            anonymous: ~
