security:

    encoders:
            Wamcar\User\BaseUser: bcrypt

    providers:
        database:
            id: AppBundle\Doctrine\Repository\DoctrineUserRepository
        api_garage_provider:
            id: AppBundle\Doctrine\Repository\DoctrineGarageRepository
        api_user_provider:
            id: AppBundle\Doctrine\Repository\DoctrineUserRepository

    role_hierarchy:
        ROLE_PRO: ROLE_USER
        ROLE_PRO_ADMIN: ROLE_USER
        ROLE_ADMIN: ROLE_PRO_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_garage:
            pattern: ^/api/v[\d]+/vehicules
            provider: api_garage_provider
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\GarageApiTokenAuthenticator

        api_user:
            pattern: ^/api/v[\d]+/user
            provider: api_user_provider
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\ApiTokenAuthenticator

        api_typeform:
            pattern: ^/api/v[\d]+/typeform/
            anonymous: ~
            stateless: true

        front:
            anonymous: ~
            form_login:
                login_path: security_login_page
                check_path: security_login_page
                default_target_path: front_view_current_user_info
                use_referer: true
                use_forward: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     front_default
                secure:   true
                always_remember_me: true
            logout:
                path:   security_logout
                target: front_default
            access_denied_url: security_login_page

            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    linkedin: "/login/check-linkedin"
                    google: "/login/check-google"
                    twitter: "/login/check-twitter"
                login_path:        security_login_page
                use_forward:       false
                failure_path:      security_login_page
                oauth_user_provider:
                    service: AppBundle\Security\UserProvider

    access_control:
        # require ROLE_PRO_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_PRO_ADMIN }
        - { path: ^/mon-profil, roles: ROLE_USER }
        - { path: ^/user/favorites, roles: ROLE_USER }
        - { path: ^/conversations, roles: ROLE_USER }
        - { path: ^/conversation, roles: ROLE_USER }
        - { path: ^/notifications, roles: ROLE_USER }
