security:

    encoders:
            Wamcar\User\BaseUser: bcrypt

    providers:
#        in_memory:
#            memory: ~

        database:
            id: AppBundle\Doctrine\Repository\DoctrineUserRepository

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        front:
            anonymous: ~
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: front_default
                use_referer: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     front_default
                secure:   true
            logout:
                path:   security_logout
                target: front_default
            access_denied_url: security_login

