security:

    encoders:
            Wamcar\User\BaseUser: bcrypt

    providers:
        database:
            id: AppBundle\Doctrine\Repository\DoctrineUserRepository
        api:
            id: AppBundle\Doctrine\Repository\DoctrineProUserRepository

    role_hierarchy:
        ROLE_PRO: ROLE_USER
        ROLE_ADMIN: ROLE_PRO
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_PRO]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/
            provider: api
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\ApiTokenAuthenticator

        front:
            anonymous: ~
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: front_default
                use_referer: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     front_default
                secure:   true
            logout:
                path:   security_logout
                target: front_default
            access_denied_url: front_default
