register_user:
    path: /inscription/particulier
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/user.html.twig

register_pro:
    path: /inscription/professionnel
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/pro.html.twig

register_confirm:
    path: /inscription/confirmation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/confirm.html.twig

reset_password:
    path: /reinitialiser-votre-mot-de-passe
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/ResetPassword/reset.html.twig

front_seller_card:
    path: /vendeur/stephane-richin
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Seller/card.html.twig

front_seller_card_edit:
    path: /vendeur/stephane-richin/editer
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Seller/edit.html.twig
