register_user:
    path: /inscription/particulier
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/user.html.twig

register_pro:
    path: /inscription/professionnel
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/pro.html.twig

reset_password:
    path: /reinitialiser-votre-mot-de-passe
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/ResetPassword/reset.html.twig

inte_seller_card:
    path: /vendeur/stephane-richin
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Seller/card.html.twig

inte_seller_card_edit:
    path: /vendeur/stephane-richin/editer
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Seller/edit.html.twig

inte_garage_detail:
    path: /garage/toyota
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Garages/Detail/detail.html.twig

inte_garage_edit:
    path: /garage/toyota/editer
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Garages/Edit/edit.html.twig

inte_vehicle_detail_pro:
    path: /vehicule/detail
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Vehicle/Detail/detail_proVehicle.html.twig


inte_vehicle_detail_personal:
    path: /vehicule/personal/detail
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Vehicle/Detail/detail_personalVehicle.html.twig


inte_vehicle_detail_pro_add:
    path: /vehicule/ajouter
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Vehicle/Add/add.html.twig

inte_vehicle_detail_pro_edit:
    path: /vehicule/editer
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Vehicle/Edit/edit.html.twig

inte_login:
    path: /inte/connexion
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Login/login.html.twig

inte_cgu:
    path: /inte/conditions-generales-utilisation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Static/cgu.html.twig

inte_search:
    path: /inte/recherche
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Search/search.html.twig

inte_user_personal_profil_edit:
    path: /inte/profil/editer
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/User/edit.html.twig
