admin_board:
    path: /
    controller: AppBundle:Front\AdministrationContext\Administration:adminBoard

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /

easy_admin_bundle:
    resource: "@AppBundle/Controller/Front/AdministrationContext/BackendController.php"
    type:     annotation
    prefix:   /backend

admin_pro_user_list:
    path: /user/pro/list
    controller: AppBundle:Front\PersonalContext\User:proUserslist

admin_pro_user_statistics:
    path: /user/pro/statistics
    controller: AppBundle:Front\PersonalContext\User:proUsersStatistics

admin_personal_user_list:
    path: /user/personal/list
    controller: AppBundle:Front\PersonalContext\User:personalUserslist

admin_personal_user_statistics:
    path: /user/personal/statistics
    controller: AppBundle:Front\PersonalContext\User:personalUsersStatistics

admin_user_linking_list:
    path: /user/relation/list
    controller: AppBundle:Front\AdministrationContext\Administration:userLinking

admin_user_linking_data:
    path: /user/relation/data
    controller: AppBundle:Front\AdministrationContext\Administration:userLinkingData

admin_user_convert_personal_to_pro:
    path: /user/convertPersonalToPro/{slug}
    controller: AppBundle:Front\PersonalContext\User:convertPersonalToPro

admin_garage_list:
    path: /garage/list
    controller: AppBundle:Front\ProContext\Garage:list

