front_default:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Home/home.html.twig

register_user_car:
    path: /inscription
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/user_car.html.twig

register_user:
    path: /inscription/particulier
    defaults:
        _controller: AppBundle:Front\Security:register

register_pro:
    path: /inscription/professionnel
    defaults:
        _controller: AppBundle:Front\Security:registerPro

register_confirm:
    path: /inscription/confirmation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/confirm.html.twig

reset_password:
    path: /reinitialiser-votre-mot-de-passe
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/ResetPassword/reset.html.twig

front_vehicle_registration:
    path: /je-vends-mon-vehicule
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration

front_vehicle_registration_form_update:
    path: /je-vends-mon-vehicule/form_update
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:updateVehicleRegistrationForm

front_user_info:
    path: /user-info
    defaults: { _controller: AppBundle:Front\PersonalContext\User:userInformations }
