front_default:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: :front:homepage.html.twig

front_vehicle_registration:
    path: /je-vends-mon-vehicule
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration
