front_default:
    path: /
    defaults:
        _controller: AppBundle:Front\Default:homepage

register:
    path: /inscription/{type}
    defaults:
        _controller: AppBundle:Front\Security:register
        type: personal

register_confirm:
    path: /inscription/confirmation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/confirm.html.twig

front_vehicle_registration:
    path: /je-vends-mon-vehicule
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration

front_vehicle_registration_form_update:
    path: /je-vends-mon-vehicule/form_update.json
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:updateVehicleRegistrationForm

front_edit_user_info:
    path: /user-info
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:editInformations

front_view_user_info:
    path: /view-user-info

front_garage_create:
    path: /garage/create
    defaults: { _controller: AppBundle:Front\ProContext\Garage:edit }

front_garage_edit:
    path: /garage/edit/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:edit }

front_seller_card:
    path: /vendeur/stephane-richin

    defaults:
        _controller: AppBundle:Front\PersonalContext\User:viewInformation

front_seller_card_edit:
    path: /vendeur/stephane-richin/editer
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Seller/edit.html.twig
