front_default:
    path: /
    defaults:
        _controller: AppBundle:Front\Default:homepage

register:
    path: /inscription/{type}
    defaults:
        _controller: AppBundle:Front\Security:register
        type: personal

register_confirm:
    path: /inscription/confirmation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/confirm.html.twig

reset_password:
    path: /reinitialiser-votre-mot-de-passe
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/ResetPassword/reset.html.twig

front_vehicle_registration:
    path: /je-vends-mon-vehicule
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration

front_vehicle_registration_form_update:
    path: /je-vends-mon-vehicule/form_update.json
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:updateVehicleRegistrationForm

front_user_info:
    path: /user-info
    defaults: { _controller: AppBundle:Front\PersonalContext\User:userInformations }

front_seller_card:
    path: /vendeur/stephane-richin
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Seller/card.html.twig
