front_default:
    path: /
    defaults:
        _controller: AppBundle:Front\Default:homepage

register:
    path: /inscription/{type}
    defaults:
        _controller: AppBundle:Front\Security:register
        type: personal

register_confirm:
    path: /inscription/confirmation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/user_confirmation.html.twig

front_vehicle_registration:
    path: /je-vends-mon-vehicule
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration

front_vehicle_registration_form_update:
    path: /je-vends-mon-vehicule/form_update.json
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:updateVehicleRegistrationForm

front_edit_user_info:
    path: /user-info
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:editInformations

front_view_current_user_info:
    path: /mon-profil
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:viewInformation

front_view_user_info:
    path: /profil/{id}
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:viewInformation

front_garage_view:
    path: /garage/view/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:view }

front_garage_create:
    path: /garage/create
    defaults: { _controller: AppBundle:Front\ProContext\Garage:save }

front_garage_edit:
    path: /garage/edit/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:save }

front_garage_list:
    path: /garage/list
    defaults: { _controller: AppBundle:Front\ProContext\Garage:index }

front_garage_remove:
    path: /garage/remove/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:remove }

front_garage_assign:
    path: /garage/assign/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:assign }

front_garage_unassign:
    path: /garage/unassign/{garage_id}/{user_id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:unassign }

front_fetch_city:
    path: /fetch/city.json
    defaults: { _controller: AppBundle:Front\PersonalContext\Registration:getCityByZipcode }

front_vehicle_pro_add:
    path: /vehicule/vendeur/ajouter/{plateNumber}
    defaults: { _controller: AppBundle:Front\ProContext\Vehicle:create, plateNumber: null }
