# Homepages & landings
front_default:
    path: /
    controller: AppBundle:Front\Default:landingMixte
    options:
        sitemap: true

legacy_landing_mixte:
    path: /m
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: front_default
        permanent: true

front_landing_reprise:
    path: /reprise
    controller: AppBundle:Front\Default:landingReprise
    options:
        sitemap: true

front_landing_meeting:
    path: /rencontre
    controller: AppBundle:Front\Default:landingMeeting
    options:
        sitemap: true

# Annuaire des conseillers automobile
front_directory_by_city_view:
    path: /annuaire-conseillers-auto/v/{city}
    controller: AppBundle:Front\ProContext\Directory:view

front_directory_view:
    path: /annuaire-conseillers-auto
    controller: AppBundle:Front\ProContext\Directory:view
    options:
        sitemap: true

legacy_directory_view:
    path: /annuaire/{page}
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: front_directory_view
        permanent: true
        page: 1

# Autocompletion des villes
front_fetch_city:
    path: /fetch/city.json
    controller: AppBundle:Front\PersonalContext\Registration:getCityByZipcode

front_city_autocomplete:
    path: /city/autocomplete
    controller: AppBundle:Front\ProContext\City:autocomplete

# Inscription
legacy_register_confirm:
    path: /inscription/confirmation
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: front_view_current_user_info
        permanent: true

register_orientation:
    path: /inscription/assistant/personal
    controller: AppBundle:Front\PersonalContext\Registration:registrationOrientation

register:
    path: /inscription/{type}
    controller: AppBundle:Front\Security:register
    defaults:
        type: personal

front_vehicle_registration_form_update:
    path: /je-vends-ma-voiture/form_update.json
    controller: AppBundle:Front\PersonalContext\Registration:updateVehicleRegistrationForm

legacy_vehicle_registration_form_update:
    path: /je-vends-mon-vehicule/form_update.json
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: front_vehicle_registration_form_update
        permanent: true

front_vehicle_registration:
    path: /je-vends-ma-voiture/{plateNumber}
    controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration
    defaults:
        plateNumber: null
    options:
        sitemap: true

legacy_vehicle_registration:
    path: /je-vends-mon-vehicule/{plateNumber}
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: front_vehicle_registration
        permanent: true
        plateNumber: null

# User
front_view_current_user_info:
    path: /mon-profil
    controller: AppBundle:Front\PersonalContext\User:currentUserViewInformation

front_user_delete:
    path: /user/delete/{id}
    controller: AppBundle:Front\PersonalContext\User:deleteUser

front_view_pro_user_info:
    path: /conseiller-auto/{slug}
    controller: AppBundle:Front\PersonalContext\User:proUserViewInformation

front_view_personal_user_info:
    path: /particulier/{slug}
    controller: AppBundle:Front\PersonalContext\User:personalUserViewInformation

front_user_edit_preferences:
    path: /preferences
    controller: AppBundle:Front\PersonalContext\User:editPreferences

front_edit_user_info:
    path: /mon-profil/edit
    controller: AppBundle:Front\PersonalContext\User:editInformations

front_edit_user_project:
    path: /mon-projet/edit
    controller: AppBundle:Front\PersonalContext\User:editProject

legacy_view_user_info:
    path: /profil/{id}
    controller: AppBundle:Front\PersonalContext\User:legacyViewInformation
    requirements:
        id: '\d+'

# Garage
front_garage_view:
    path: /g/{slug}
    controller: AppBundle:Front\ProContext\Garage:view

legacy_garage_view:
    path: /garage/view/{id}
    controller: AppBundle:Front\ProContext\Garage:legacyView

front_garage_create:
    path: /garage/create
    controller: AppBundle:Front\ProContext\Garage:save

front_garage_edit:
    path: /garage/edit/{id}
    controller: AppBundle:Front\ProContext\Garage:save

# Gestion des membres d'un garage
front_garage_request_to_join:
    path: /garage/request/{garage_id}
    controller: AppBundle:Front\ProContext\Garage:assign

front_garage_assign:
    path: /garage/assign/{garage_id}/{user_id}
    controller: AppBundle:Front\ProContext\Garage:assign

front_garage_unassign:
    path: /garage/unassign/{garage_id}/{user_id}
    controller: AppBundle:Front\ProContext\Garage:unassign

front_garage_toogle_member_role:
    path: /garage/memberrole/toogle/{garage_id}/{user_id}
    controller: AppBundle:Front\ProContext\Garage:toogleMemberRole

# Vehicles professionnels
front_vehicle_pro_detail:
    path: /voiture-pro/{slug}
    controller: AppBundle:Front\ProContext\Vehicle:detail
    requirements:
        slug: '.+'

legacy_vehicle_pro_detail:
    path: /vehicule/detail/{id}
    controller: AppBundle:Front\ProContext\Vehicle:legacyDetail

front_vehicle_pro_add:
    path: /vehicule/vendeur/ajouter/{garage_id}/{plateNumber}
    controller: AppBundle:Front\ProContext\Vehicle:save
    defaults:
      plateNumber: null
      vehicle: null
    requirements:
        garage_id: '\d+'

front_vehicle_pro_edit:
    path: /vehicule/vendeur/modifier/{vehicle_id}/{plateNumber}
    controller: AppBundle:Front\ProContext\Vehicle:save
    defaults:
      garage: null
      plateNumber: null

front_vehicle_pro_reassign:
    path: /vehicule/reassign/{vehicle_id}
    controller: AppBundle:Front\ProContext\Vehicle:assign

front_vehicle_pro_assign_seller:
    path: /vehicule/assign/{vehicle_id}/{pro_user_id}
    controller: AppBundle:Front\ProContext\Vehicle:assign

front_vehicle_pro_delete:
    path: /vehicule/delete/{id}
    controller: AppBundle:Front\ProContext\Vehicle:delete

# Vehicules particuliers
front_vehicle_personal_detail:
    path: /voiture-particulier/{slug}
    controller: AppBundle:Front\ProContext\PersonalVehicle:detail
    requirements:
        slug: '.+'

legacy_vehicle_personal_detail:
    path: /vehicule/particulier/detail/{id}
    controller: AppBundle:Front\ProContext\PersonalVehicle:legacyDetail

front_vehicle_personal_add:
    path: /vehicule/particulier/ajouter/{plateNumber}
    controller: AppBundle:Front\ProContext\PersonalVehicle:save
    defaults:
      plateNumber: null
      vehicle: null

front_vehicle_personal_edit:
    path: /vehicule/particulier/{id}/modifier/{plateNumber}
    controller: AppBundle:Front\ProContext\PersonalVehicle:save
    defaults:
      plateNumber: null

front_vehicle_personal_delete:
    path: /vehicule/particulier/delete/{id}
    controller: AppBundle:Front\ProContext\PersonalVehicle:delete

# Search
front_search_by_city:
    path: /recherche-voitures/v/{city}
    controller: AppBundle:Front\ProContext\Search:search

front_search_by_make:
    path: /recherche-voitures/m/{make}
    controller: AppBundle:Front\ProContext\Search:search

front_search_by_make_model:
    path: /recherche-voitures/m/{make}/{model}
    controller: AppBundle:Front\ProContext\Search:search

front_search:
    path: /recherche-voitures
    controller: AppBundle:Front\ProContext\Search:search
    options:
        sitemap: true

legacy_search:
    path: /recherche/{page}
    controller: FrameworkBundle:Redirect:urlRedirect
    defaults:
        path: /recherche-voitures
        permanent: true
        page: 1
    requirements:
        page: '\d+'

# Messagerie
front_conversation_vehicle_list:
    path: /conversation/ajouter-vehicule/
    controller: AppBundle:Front\ProContext\Conversation:vehicleList

front_conversation_create:
    path: /conversation/new/{id}/{vehicleId}
    controller: AppBundle:Front\ProContext\Conversation:create
    defaults:
        vehicleId: null

front_conversation_edit:
    path: /conversation/{id}/{vehicleId}
    controller: AppBundle:Front\ProContext\Conversation:edit
    defaults:
        vehicleId: null

front_conversation_list:
    path: /conversations
    controller: AppBundle:Front\ProContext\Conversation:index

# Vehicle Likes
front_user_like_pro_vehicle:
    path: /user/like/pro/{id}
    controller: AppBundle:Front\ProContext\Vehicle:likeProVehicle

front_user_like_personal_vehicle:
    path: /user/like/personal/{id}
    controller: AppBundle:Front\ProContext\PersonalVehicle:likePersonalVehicle

front_user_favorites_list:
    path: /user/favorites
    controller: AppBundle:Front\ProContext\Favorite:view

# Wamcar Affinity
front_affinity_personal_form:
    path: /affinity/particulier
    controller: AppBundle:Front\PersonalContext\Affinity:personalForm

front_affinity_personal_redirection:
    path: /affinity/particulier/soumis
    controller: AppBundle:Front\PersonalContext\Affinity:personalFormSubmited

front_affinity_pro_form:
    path: /affinity/professionnel
    controller: AppBundle:Front\PersonalContext\Affinity:proForm

front_affinity_pro_redirection:
    path: /affinity/professionnel/soumis
    controller: AppBundle:Front\PersonalContext\Affinity:proFormSubmited

# Administration
front_user_list:
    path: /user/list
    controller: AppBundle:Front\PersonalContext\User:list

front_garage_list:
    path: /garage/list
    controller: AppBundle:Front\ProContext\Garage:list

front_garage_remove:
    path: /garage/remove/{id}
    controller: AppBundle:Front\ProContext\Garage:remove

