front_default:
    path: /
    defaults:
        _controller: AppBundle:Front\Default:homepage

register:
    path: /inscription/{type}
    defaults:
        _controller: AppBundle:Front\Security:register
        type: personal

register_confirm:
    path: /inscription/confirmation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/user_confirmation.html.twig

front_vehicle_registration_form_update:
    path: /je-vends-mon-vehicule/form_update.json
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:updateVehicleRegistrationForm

front_vehicle_registration:
    path: /je-vends-mon-vehicule/{plateNumber}
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration
        plateNumber: null

front_edit_user_info:
    path: /user-info
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:editInformations

front_view_current_user_info:
    path: /mon-profil
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:viewInformation

front_view_user_info:
    path: /profil/{id}
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:viewInformation

front_garage_view:
    path: /garage/view/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:view }

front_garage_create:
    path: /garage/create
    defaults: { _controller: AppBundle:Front\ProContext\Garage:save }

front_garage_edit:
    path: /garage/edit/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:save }

front_garage_list:
    path: /garage/list
    defaults: { _controller: AppBundle:Front\ProContext\Garage:index }

front_garage_remove:
    path: /garage/remove/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:remove }

front_garage_assign:
    path: /garage/assign/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:assign }

front_garage_unassign:
    path: /garage/unassign/{garage_id}/{user_id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:unassign }

front_fetch_city:
    path: /fetch/city.json
    defaults: { _controller: AppBundle:Front\PersonalContext\Registration:getCityByZipcode }

front_vehicle_pro_add:
    path: /vehicule/vendeur/ajouter/{plateNumber}
    defaults: { _controller: AppBundle:Front\ProContext\Vehicle:save, plateNumber: null, vehicle: null  }

front_vehicle_pro_edit:
    path: /vehicule/vendeur/{id}/modifier/{plateNumber}
    defaults: { _controller: AppBundle:Front\ProContext\Vehicle:save, plateNumber: null }

front_vehicle_pro_detail:
    path: /vehicule/detail/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Vehicle:detail }

front_vehicle_pro_delete:
    path: /vehicule/delete/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Vehicle:delete }

front_vehicle_personal_add:
    path: /vehicule/particulier/ajouter/{plateNumber}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:save, plateNumber: null, vehicle: null  }

front_vehicle_personal_edit:
    path: /vehicule/particulier/{id}/modifier/{plateNumber}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:save, plateNumber: null }

front_vehicle_personal_detail:
    path: /vehicule/particulier/detail/{id}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:detail }

front_vehicle_personal_delete:
    path: /vehicule/particulier/delete/{id}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:delete }

front_search_pro:
    path: /vendeur/rechercher
    defaults:
        _controller: AppBundle:Front\ProContext\Search:pro
        type: 'ALL'

front_search_pro_page:
    path: /vendeur/rechercher/{page}
    defaults:
        _controller: AppBundle:Front\ProContext\Search:pro
        page: 1
        type: 'ALL'

front_search_pro_page_recovery:
    path: /vendeur/rechercher/reprise/{page}
    defaults:
        _controller: AppBundle:Front\ProContext\Search:pro
        page: 1
        type: 'RECOVERY'

front_search_pro_page_project:
    path: /vendeur/rechercher/souhait/{page}
    defaults:
        _controller: AppBundle:Front\ProContext\Search:pro
        page: 1
        type: 'PROJECT'

front_search_personal:
    path: /utilisateur/rechercher
    defaults:
        _controller: AppBundle:Front\ProContext\Search:personal

front_search_personal_page:
    path: /utilisateur/rechercher/{page}
    defaults:
        _controller: AppBundle:Front\ProContext\Search:personal
        page: 1
