front_default:
    path: /
    controller: AppBundle:Front\Default:landingMixte

# legacy
front_landing_mixte:
    path: /m
    controller: AppBundle:Front\Default:landingMixte

front_landing_reprise:
    path: /reprise
    controller: AppBundle:Front\Default:landingReprise

front_landing_meeting:
    path: /rencontre
    controller: AppBundle:Front\Default:landingMeeting

front_directory_view:
    path: /annuaire/{page}
    controller: AppBundle:Front\ProContext\Directory:view
    defaults:
        page: 1

# deprecated
register_confirm:
    path: /inscription/confirmation
    defaults:
        _controller: FrameworkBundle:Template:template
        template: front/Security/Register/user_confirmation.html.twig

register_orientation:
    path: /inscription/assistant/personal/
    controller: AppBundle:Front\PersonalContext\Registration:registrationOrientation

register:
    path: /inscription/{type}
    defaults:
        _controller: AppBundle:Front\Security:register
        type: personal

front_vehicle_registration_form_update:
    path: /je-vends-mon-vehicule/form_update.json
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:updateVehicleRegistrationForm

front_vehicle_registration:
    path: /je-vends-mon-vehicule/{plateNumber}
    defaults:
        _controller: AppBundle:Front\PersonalContext\Registration:vehicleRegistration
        plateNumber: null

front_edit_user_info:
    path: /mon-profil/edit
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:editInformations

front_edit_user_project:
    path: /mon-projet/edit
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:editProject

front_view_current_user_info:
    path: /mon-profil
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:viewInformation

front_view_user_info:
    path: /profil/{id}
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:viewInformation

front_user_list:
    path: /user/list
    defaults:
        _controller: AppBundle:Front\PersonalContext\User:list

front_user_edit_preferences:
    path: /preferences
    controller: AppBundle:Front\PersonalContext\User:editPreferences

front_garage_view:
    path: /garage/view/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:view }

front_garage_create:
    path: /garage/create
    defaults: { _controller: AppBundle:Front\ProContext\Garage:save }

front_garage_edit:
    path: /garage/edit/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:save }

front_garage_list:
    path: /garage/list
    defaults: { _controller: AppBundle:Front\ProContext\Garage:index }

front_garage_remove:
    path: /garage/remove/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:remove }

front_garage_request_to_join:
    path: /garage/request/{garage_id}
    controller: AppBundle:Front\ProContext\Garage:assign

front_garage_assign:
    path: /garage/assign/{garage_id}/{user_id}
    controller: AppBundle:Front\ProContext\Garage:assign

front_garage_unassign:
    path: /garage/unassign/{garage_id}/{user_id}
    defaults: { _controller: AppBundle:Front\ProContext\Garage:unassign }

front_fetch_city:
    path: /fetch/city.json
    defaults: { _controller: AppBundle:Front\PersonalContext\Registration:getCityByZipcode }

front_vehicle_pro_add:
    path: /vehicule/vendeur/ajouter/{garage_id}/{plateNumber}
    requirements:
        garage_id: '\d+'
    defaults:
      _controller: AppBundle:Front\ProContext\Vehicle:save
      plateNumber: null
      vehicle: null

front_vehicle_pro_edit:
    path: /vehicule/vendeur/modifier/{vehicle_id}/{plateNumber}
    defaults:
      _controller: AppBundle:Front\ProContext\Vehicle:save
      garage: null
      plateNumber: null

front_vehicle_pro_reassign:
    path: /vehicule/reassign/{vehicle_id}
    controller: AppBundle:Front\ProContext\Vehicle:assign

front_vehicle_pro_assign_seller:
    path: /vehicule/assign/{vehicle_id}/{pro_user_id}
    controller: AppBundle:Front\ProContext\Vehicle:assign

front_vehicle_pro_detail:
    path: /vehicule/detail/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Vehicle:detail }

front_vehicle_pro_delete:
    path: /vehicule/delete/{id}
    defaults: { _controller: AppBundle:Front\ProContext\Vehicle:delete }

front_vehicle_personal_add:
    path: /vehicule/particulier/ajouter/{plateNumber}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:save, plateNumber: null, vehicle: null  }

front_vehicle_personal_edit:
    path: /vehicule/particulier/{id}/modifier/{plateNumber}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:save, plateNumber: null }

front_vehicle_personal_detail:
    path: /vehicule/particulier/detail/{id}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:detail }

front_vehicle_personal_delete:
    path: /vehicule/particulier/delete/{id}
    defaults: { _controller: AppBundle:Front\ProContext\PersonalVehicle:delete }

front_search:
    path: /recherche/{page}
    controller: AppBundle:Front\ProContext\Search:search
    requirements:
        page: '\d+'
    defaults:
        page: 1

#front_search_tab_all:
#    path: /recherche/{page}
#    controller: AppBundle:Front\ProContext\Search:search
#    requirements:
#        page: '\d+'
#    defaults:
#        page: 1
#        type: 'TAB_ALL'
#
#front_search_tab_personal:
#    path: /recherche/{page}
#    controller: AppBundle:Front\ProContext\Search:search
#    requirements:
#        page: '\d+'
#    defaults:
#        page: 1
#        type: 'TAB_PERSONAL'
#
#front_search_tab_pro:
#    path: /recherche/{page}
#    controller: AppBundle:Front\ProContext\Search:search
#    requirements:
#        page: '\d+'
#    defaults:
#        page: 1
#        type: 'TAB_PRO'
#
#front_search_tab_project:
#    path: /recherche/{page}
#    controller: AppBundle:Front\ProContext\Search:search
#    requirements:
#        page: '\d+'
#    defaults:
#        page: 1
#        type: 'TAB_PROJECT'

#front_search_pro:
#    path: /vendeur/rechercher
#    defaults:
#        _controller: AppBundle:Front\ProContext\Search:pro
#        type: 'ALL'
#
#front_search_pro_page:
#    path: /vendeur/rechercher/{page}
#    defaults:
#        _controller: AppBundle:Front\ProContext\Search:pro
#        page: 1
#        type: 'ALL'
#
#front_search_pro_page_recovery:
#    path: /vendeur/rechercher/reprise/{page}
#    defaults:
#        _controller: AppBundle:Front\ProContext\Search:pro
#        page: 1
#        type: 'RECOVERY'
#
#front_search_pro_page_project:
#    path: /vendeur/rechercher/souhait/{page}
#    defaults:
#        _controller: AppBundle:Front\ProContext\Search:pro
#        page: 1
#        type: 'PROJECT'
#
#front_search_personal:
#    path: /utilisateur/rechercher
#    defaults:
#        _controller: AppBundle:Front\ProContext\Search:personal

#front_search_personal_page:
#    path: /utilisateur/rechercher/{page}
#    defaults:
#        _controller: AppBundle:Front\ProContext\Search:personal
#        page: 1

front_conversation_vehicle_list:
    path: /conversation/ajouter-vehicule/
    defaults:
        _controller: AppBundle:Front\ProContext\Conversation:vehicleList

front_conversation_create:
    path: /conversation/new/{id}/{vehicleId}
    defaults:
        _controller: AppBundle:Front\ProContext\Conversation:create
        vehicleId: null

front_conversation_edit:
    path: /conversation/{id}/{vehicleId}
    defaults:
        _controller: AppBundle:Front\ProContext\Conversation:edit
        vehicleId: null

front_conversation_list:
    path: /conversations
    defaults: { _controller: AppBundle:Front\ProContext\Conversation:index }

front_city_autocomplete:
    path: /city/autocomplete
    defaults: { _controller: AppBundle:Front\ProContext\City:autocomplete }

front_user_like_pro_vehicle:
    path: /user/like/pro/{id}
    defaults:
        _controller: AppBundle:Front\ProContext\Vehicle:likeProVehicle

front_user_like_personal_vehicle:
    path: /user/like/personal/{id}
    defaults:
        _controller: AppBundle:Front\ProContext\PersonalVehicle:likePersonalVehicle

front_user_favorites_list:
    path: /user/favorites
    controller: AppBundle:Front\ProContext\Favorite:view