services:

    wamcar.app.controller.base:
        abstract: true
        calls:
            - [setLogger, [ '@logger' ]]
            - [setTemplatingEngine, [ '@templating' ]]
            - [setRouter, [ '@router' ]]
            - [setSession, [ '@session' ]]
            - [setTokenStorage, [ '@security.token_storage' ]]

        tags:
            - { name: monolog.logger, channel: controllers }

    wamcar.app.controller.security:
        class: AppBundle\Controller\SecurityController
        parent: wamcar.app.controller.base
        arguments:
            - '@form.factory'
            - '@wamcar.security.user_registration_service'
            - '@security.authentication_utils'
            - '@wamcar.repository.user.doctrine'
