front:
    resource: "routing/front.yml"
    prefix: /

# Security processes
security_register:
    path: /inscription
    defaults:
        _controller: AppBundle:Front\Security:register
        context: Personal

security_register_pro:
    path: /inscription/pro
    defaults:
        _controller: AppBundle:Front\Security:register
        context: Pro
