front:
    resource: "routing/front.yml"
    prefix: /

# Security processes
security_register:
    path: /inscription
    defaults:
        _controller: AppBundle:Front\Security:register

security_register_pro:
    path: /inscription/pro
    defaults:
        _controller: AppBundle:Front\Security:registerPro

security_confirm_registration:
    path: /confirmer-votre-inscription/{token}
    defaults: { _controller: AppBundle:Front\Security:confirmRegistration }
