front:
    resource: "routing/front.yml"
    prefix: /

notifications:
    resource: "routing/notifications.yml"
    prefix: /notifications/

static:
    resource: "routing/static.yml"
    prefix: /

api:
    resource: "routing/api.yml"
    prefix: /api/

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

# Security processes
security_login_page:
    path: /connexion
    defaults: { _controller: AppBundle:Front\Security:loginPage }

security_logout:
    path: /deconnexion

security_confirm_registration:
    path: /confirmer-votre-inscription/{token}
    defaults: { _controller: AppBundle:Front\Security:confirmRegistration }

security_password_lost:
    path: /mot-de-passe-oublie
    defaults: { _controller: AppBundle:Front\Security:passwordLost }

security_password_reset:
    path: /reinitialiser-votre-mot-de-passe/{token}
    defaults: { _controller: AppBundle:Front\Security:passwordLostReset }

# HwiOAuth
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect

hwi_oauth_service_redirect:
    path: /connect/{service}
    defaults: { _controller: AppBundle:Front\Security:redirectToService }

facebook_login:
    path: /login/check-facebook
linkedin_login:
    path: /login/check-linkedin
google_login:
    path: /login/check-google
twitter_login:
    path: /login/check-twitter
