# B2B model
#front:
#    resource: "routing/front.yml"
#    prefix: /

legacy_front:
  resource: "routing/front.yml"
  prefix: /

b2b:
  resource: "routing/front_b2b.yml"
  prefix: /

admin:
  resource: "routing/admin.yml"
  prefix: /admin

notifications:
  resource: "routing/notifications.yml"
  prefix: /notifications/

static:
  resource: "routing/static.yml"
  prefix: /
  options:
    sitemap: true

# B2B model
#api:
#    resource: "routing/api.yml"
#    prefix: /api/

_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"

# Security processes
security_login_page:
  path: /connexion
  defaults: { _controller: AppBundle:Front\Security:loginPage }
  options:
    sitemap: true

security_logout:
  path: /deconnexion

# B2B model
#security_confirm_registration:
#    path: /confirmer-votre-inscription/{token}
#    defaults: { _controller: AppBundle:Front\Security:confirmRegistration }

security_password_lost:
  path: /mot-de-passe-oublie
  defaults: { _controller: AppBundle:Front\Security:passwordLost }

security_password_reset:
  path: /reinitialiser-votre-mot-de-passe/{token}
  defaults: { _controller: AppBundle:Front\Security:passwordLostReset }

# HwiOAuth
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect

hwi_oauth_service_redirect:
  path: /connect/{service}
  defaults: { _controller: AppBundle:Front\Security:redirectToService }

facebook_login:
  path: /login/check-facebook
linkedin_login:
  path: /login/check-linkedin
google_login:
  path: /login/check-google
twitter_login:
  path: /login/check-twitter
