parameters:
    wamcar.search.config:
        settings:
            number_of_shards : 1
            number_of_replicas : 1
            analysis:
                analyzer:
                    default:
                        type:         custom
                        tokenizer:    nGram
                        filter:       [stopwords, asciifolding, uppercase, elision, worddelimiter, snowball]
                        char_filter:  [custom_char_filter]
                    default_search:
                        type:         custom
                        tokenizer:    standard
                        filter:       [asciifolding, uppercase, elision, worddelimiter, snowball]
                tokenizer:
                    nGram:
                        type:       nGram
                        min_gram:   3
                        max_gram:   15
                filter:
                    stopwords:
                        type:       stop
                        stopwords:  [_french_]
                        ignore_case: true
                    snowball:
                        type:       snowball
                        language:   French
                    worddelimiter:
                        type:       word_delimiter
                    elision:
                         type:      elision
                         articles:  [l, m, t, qu, n, s, j, d]
                char_filter:
                    custom_char_filter:
                        type: html_strip
        mappings:
            vehicle_info:
                _source : { enabled : true }
                properties:
                    ktypNumber:
                        type: string
                        index: not_analyzed
                    make:
                        type: string
                        index: not_analyzed
                    model:
                        type: string
                        index: not_analyzed
                    modelVersion:
                        type: string
                        index: not_analyzed
                    engineCode:
                        type: string
                        index: not_analyzed
                    engine:
                        type: string
                        index: not_analyzed
                    startDate:
                        type: date
                        index: not_analyzed
                    endDate:
                        type: date
                        index: not_analyzed
                    engineSize:
                        type: float
                        index: not_analyzed
                    horsePower:
                        type: integer
                        index: not_analyzed
                    body:
                        type: string
                        index: not_analyzed
                    wheelDrive:
                        type: string
                        index: not_analyzed
                    fuel:
                        type: string
                        index: not_analyzed
                    nbCylinders:
                        type: integer
                        index: not_analyzed
                    nbValve:
                        type: integer
                        index: not_analyzed
            pro_vehicle:
                _source : { enabled : true }
            personal_vehicle:
                _source : { enabled : true }
                properties:
                    location:
                        type: geo_point
                    mileage:
                        type: integer
                    years:
                        type: integer
                    transmission:
                        type: string
                        index: not_analyzed

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Novaway\ElasticsearchClient\Index:
        arguments:
            - ['%env(ELASTIC_HOST)%:%env(ELASTIC_PORT)%'] #define it in the parameter.yml file
            - 'wamcar_index_%env(ELASTIC_ENVIRONMENT)%'
            - '%wamcar.search.config%'

    Novaway\ElasticsearchClient\ObjectIndexer: ~
    Novaway\ElasticsearchClient\QueryExecutor: ~
    Novaway\ElasticsearchClient\Query\ResultTransformer: ~
