imports:
    - { resource: services/utils.yml }
    - { resource: services/forms.yml }
    - { resource: services/controllers.yml }
    - { resource: services/repositories.yml }
    - { resource: services/events.yml }
    - { resource: services/mail.yml }
    - { resource: services/autodata.yml }
    - { resource: search.yml }

services:

    SimpleBus\Message\Bus\MessageBus: '@simple_bus.event_bus'

    # SECURITY
    wamcar.security.password_encoder:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: ['@security.encoder_factory', 'getEncoder']
        arguments: [Wamcar\User\BaseUser]

    AppBundle\Security\UserRegistrationService:
        class: AppBundle\Security\UserRegistrationService
        arguments:
            - '@wamcar.security.password_encoder'
            - '@AppBundle\Doctrine\Repository\DoctrineUserRepository'
            - '@event_bus'
            - '@logger'

    AppBundle\Services\User\UserEditionService:
        class: AppBundle\Services\User\UserEditionService
        arguments:
            - '@wamcar.security.password_encoder'
            - '@AppBundle\Doctrine\Repository\DoctrineUserRepository'
            - '@AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository'
            - '@AppBundle\Doctrine\Repository\DoctrineProUserRepository'
