imports:
    - { resource: services/forms.yml }
    - { resource: services/controllers.yml }
    - { resource: services/repositories.yml }
    - { resource: services/events.yml }
    - { resource: search.yml }

services:
    # SECURITY
    wamcar.security.password_encoder:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: ['@security.encoder_factory', 'getEncoder']
        arguments: [Wamcar\User\BaseUser]

    AppBundle\Security\UserRegistrationService:
        class: AppBundle\Security\UserRegistrationService
        arguments:
            - '@wamcar.security.password_encoder'
            - '@AppBundle\Doctrine\Repository\DoctrineUserRepository'
            - '@event_bus'

    wamcar.mail_workflow.mailer:
        class: AppBundle\MailWorkflow\Services\Mailer
        arguments:
            - '@mailer'
            - '%mailer%'
            - '@logger'
