imports:
    - { resource: services/utils.yml }
    - { resource: services/forms.yml }
    - { resource: services/controllers.yml }
    - { resource: services/builders.yml }
    - { resource: services/repositories.yml }
    - { resource: services/events.yml }
    - { resource: services/mail.yml }
    - { resource: services/autodata.yml }
    - { resource: services/voters.yml }
    - { resource: services/extensions.yml }
    - { resource: services/pictures.yml }
    - { resource: services/validators.yml }
    - { resource: services/sessions.yml }
    - { resource: search.yml }

services:

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    SimpleBus\Message\Bus\MessageBus: '@simple_bus.event_bus'

    Liip\ImagineBundle\Imagine\Cache\CacheManager: '@liip_imagine.cache.manager'

    VichUploader\Templating\Helper\UploaderHelper: '@vich_uploader.templating.helper.uploader_helper'

    PragmaRX\ZipCode\ZipCode:
        class: 'PragmaRX\ZipCode\ZipCode'
        calls:
          - ['setCountry', ['FR']]

    # SECURITY
    wamcar.security.password_encoder:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: ['@security.encoder_factory', 'getEncoder']
        arguments: [Wamcar\User\BaseUser]

    AppBundle\Security\UserRegistrationService:
        class: AppBundle\Security\UserRegistrationService
        arguments:
            - '@wamcar.security.password_encoder'
            - '@AppBundle\Doctrine\Repository\DoctrineUserRepository'
            - '@event_bus'
            - '@logger'

    AppBundle\Services\User\UserEditionService:
        class: AppBundle\Services\User\UserEditionService
        arguments:
            - '@wamcar.security.password_encoder'
            - '@AppBundle\Doctrine\Repository\DoctrineUserRepository'
            - {AppBundle\Doctrine\Entity\PersonalApplicationUser: '@AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository', AppBundle\Doctrine\Entity\ProApplicationUser: '@AppBundle\Doctrine\Repository\DoctrineProUserRepository'}
            - '@AppBundle\Form\Builder\User\ProjectFromDTOBuilder'
            - '@AppBundle\Doctrine\Repository\DoctrineProjectRepository'

    AppBundle\Security\ApiTokenAuthenticator:
        autowire: true

    AppBundle\Services\Garage\GarageEditionService:
        class: AppBundle\Services\Garage\GarageEditionService
        public: false
        autowire: true
        autoconfigure: false

    AppBundle\Services\Conversation\ConversationEditionService:
        class: AppBundle\Services\Conversation\ConversationEditionService
        public: false
        autowire: true
        autoconfigure: false

    AppBundle\Services\Conversation\ConversationAuthorizationChecker:
        class: AppBundle\Services\Conversation\ConversationAuthorizationChecker
        public: false
        autowire: true
        autoconfigure: false

    AppBundle\Services\Vehicle\VehicleRepositoryResolver:
        class: AppBundle\Services\Vehicle\VehicleRepositoryResolver
        autowire: true
