AppBundle\Doctrine\Entity\ProApplicationUser:

    type: entity
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineProUserRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false

    exclusion_policy: ALL

    fields:
        password:
            type: string
        salt:
            type: string
        passwordResetToken:
            type: string
            length: 32
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: date
            nullable: true
        apiClientId:
            type: string
            nullable: true
        apiSecret:
            type: string
            nullable: true
