AppBundle\Doctrine\Entity\ProApplicationUser:

    type: entity
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineProUserRepository
    exclusion_policy: ALL

    fields:
        password:
            type: string
        salt:
            type: string
        passwordResetToken:
            type: string
            length: 32
            nullable: true
        role:
            type: string
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create