AppBundle\Doctrine\Entity\PersonalVehiclePicture:

    type: entity

    exclusion_policy: ALL

    fields:
        position:
            type: integer
            gedmo:
                - sortablePosition

    manyToOne:
        vehicle:
            targetEntity: Wamcar\Vehicle\PersonalVehicle
            inversedBy: pictures
            joinColumn:
                name: vehicle_id
                referencedColumnName: id
            gedmo:
                - sortableGroup
