AppBundle\Doctrine\Entity\PersonalApplicationUser:

    type: entity
    repositoryClass: AppBundle\Doctrine\Repository\DoctrinePersonalUserRepository
    exclusion_policy: ALL

    fields:
        password:
            type: string
        salt:
            type: string
        registrationToken:
            type: string
            length: 32
            nullable: true
            unique: true
        passwordResetToken:
            type: string
            length: 32
            nullable: true
            unique: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
