AppBundle\Doctrine\Entity\VehiclePicture:

    type: entity
    inheritanceType: SINGLE_TABLE
    table: vehicle_picture
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        abstract: AppBundle\Doctrine\Entity\VehiclePicture
        pro: AppBundle\Doctrine\Entity\ProVehiclePicture
        perso: AppBundle\Doctrine\Entity\PersonalVehiclePicture

    exclusion_policy: ALL

    id:
        id:
            type: uuid

    fields:
        caption:
            type: string
            nullable: true
        fileName:
            type: string
        fileSize:
            type: integer
        fileMimeType:
            type: string
        fileOriginalName:
            type: string
