AppBundle\Doctrine\Entity\GarageBanner:

    type: entity

    exclusion_policy: ALL

    oneToOne:
        garage:
            targetEntity: Wamcar\Garage\Garage
            inversedBy: banner
            joinColumn:
                name: garage_id
                referencedColumnName: id
