AppBundle\Doctrine\Entity\UserPreferences:

    type: entity
    table: user_preferences

    repositoryClass: AppBundle\Doctrine\Repository\DoctrineUserPreferencesRepository

    id:
        user:
            associationKey: true

    fields:
        globalEmailFrequency:
            type: notificationfrequency
        privateMessageEmailEnabled:
            type: boolean
        privateMessageEmailFrequency:
            type: notificationfrequency
        likeEmailEnabled:
              type: boolean
        likeEmailFrequency:
            type: notificationfrequency
        leadEmailEnabled:
            type: boolean
        leadOnlyPartExchange:
            type: boolean
        leadOnlyProject:
            type: boolean
        leadProjectWithPartExchange:
            type: boolean
        leadLocalizationRadiusCriteria:
            type: integer
        leadPartExchangeKmMaxCriteria:
            type: integer
        leadProjectBudgetMinCriteria:
            type: integer

    oneToOne:
        user:
            targetEntity: Wamcar\User\BaseUser
            inversedBy: preferences
            joinColumn:
                name: user_id
                referencedColumnName: id
