AppBundle\Doctrine\Entity\ProVehiclePicture:

    type: entity

    exclusion_policy: ALL

    fields:
        position:
            type: integer
            gedmo:
                - sortablePosition

    manyToOne:
        vehicle:
            targetEntity: Wamcar\Vehicle\ProVehicle
            inversedBy: pictures
            joinColumn:
                name: vehicle_id
                referencedColumnName: id
            orderBy:
                position: 'ASC'
            gedmo:
                - sortableGroup
