AppBundle\Doctrine\Entity\ProApplicationUser:

    type: entity
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineUserRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false

    exclusion_policy: ALL

    fields:
        password:
            type: string
        salt:
            type: string
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: date
            nullable: true
