AppBundle\Doctrine\Entity\AffinityDegree:

    type: entity
    table: affinity_degree
    repositoryClass: AppBundle\Doctrine\Repository\DoctrineAffinityDegreeRepository

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [proUser, personalUser ]
            errorPath: proUser
            message: 'The affinity between these users is already calculated.'

    id:
      mainUser:
        associationKey: true
      withUser:
        associationKey: true

    fields:
      affinityValue:
        type: float
        nullable: false

    manyToOne:
        mainUser:
            targetEntity: Wamcar\User\BaseUser
            inversedBy: myAffinityDegrees
            joinColumn:
                name: main_user_id
                referencedColumnName: id
        withUser:
            targetEntity: Wamcar\User\BaseUser
            joinColumn:
                name: with_user_id
                referencedColumnName: id
