AppBundle\Doctrine\Entity\UserBanner:
    file:
        mapping:           user_banner
        filename_property: fileName
        size:              fileSize
        mime_type:         fileMimeType
        original_name:     fileOriginalName
