AppBundle\Doctrine\Entity\GarageLogo:
    file:
        mapping:           garage_logo
        filename_property: fileName
        size:              fileSize
        mime_type:         fileMimeType
        original_name:     fileOriginalName
