AppBundle\Doctrine\Entity\GarageBanner:
    file:
        mapping:           garage_banner
        filename_property: fileName
        size:              fileSize
        mime_type:         fileMimeType
        original_name:     fileOriginalName
