AppBundle\Doctrine\Entity\VideoProjectBanner:
  file:
    mapping:           videoproject_banner
    filename_property: fileName
    size:              fileSize
    mime_type:         fileMimeType
    original_name:     fileOriginalName
