AppBundle\Doctrine\Entity\UserPicture:
    file:
        mapping:           user_image
        filename_property: fileName
        size:              fileSize
        mime_type:         fileMimeType
        original_name:     fileOriginalName
