AppBundle\Doctrine\Entity\VehiclePicture:
    file:
        mapping:           vehicle_image
        filename_property: fileName
        size:              fileSize
        mime_type:         fileMimeType
        original_name:     fileOriginalName
