Wamcar\Conversation\MessageAttachment:
    file:
        mapping:           message_attachment
        filename_property: fileName
        size:              fileSize
        mime_type:         fileMimeType
        original_name:     fileOriginalName
